(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var r2=function(a){a.V("cardstatechange",g.RT(a)&&g.ST(a)?1:0)},pDa=function(a){var b=g.Eg(a);
a=g.Lg(a);return new g.jg(b.x,b.y,a.width,a.height)},qDa=function(a){return Math.pow(a,3)},rDa=function(a){return 3*a*a-2*a*a*a},u2=function(a){a=g.Ra(a);
delete s2[a];g.Sb(s2)&&t2&&t2.stop()},tDa=function(){t2||(t2=new g.F(function(){sDa()},20));
var a=t2;a.isActive()||a.start()},sDa=function(){var a=g.A();
g.Eb(s2,function(b){uDa(b,a)});
g.Sb(s2)||tDa()},v2=function(a,b,c,d){g.vn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.K=b;this.duration=c;this.F=d;this.coords=[];this.progress=this.I=0;this.D=null},uDa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.I=1E3/(b-a.D);a.D=b;vDa(a,a.progress);1==a.progress?(a.Ka=0,u2(a),a.ag(),a.ur()):a.Hb()&&a.oy()},vDa=function(a,b){"function"===typeof a.F&&(b=a.F(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.K[c]-a.u[c])*b+a.u[c]},wDa=function(a,b){g.El.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.I;this.state=b.Ka},w2=function(a,b,c,d,e){v2.call(this,b,c,d,e);
this.element=a},x2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
w2.call(this,a,b,c,d,e)},y2=function(a){g.C.call(this);
this.B=a||window;this.u=[]},z2=function(a){return a.baseUrl||null},A2=function(a,b){return g.Ke(g.Oc(a,b,void 0),function(c){return!!c})},xDa=function(a,b,c){function d(Oa){var Sa,Xa,kc,Yb=Oa.hovercardButton;
if(!Yb)return null;Yb=Yb.subscribeButtonRenderer;if(!Yb)return null;var Qe=f(Yb.unsubscribedButtonText),ue=f(Yb.subscribedButtonText);if(Yb.subscribed){var mf=f(Yb.subscriberCountWithUnsubscribeText);var Uf=f(Yb.subscriberCountText)}else mf=f(Yb.subscriberCountText),Uf=f(Yb.subscriberCountWithSubscribeText);var Qc=null;return Oa.signinEndpoint&&(Qc=g.Nb(Oa,"signinEndpoint","webNavigationEndpointData","url"),Qc||(Qc=null===(kc=null===(Xa=null===(Sa=Yb.signInEndpoint)||void 0===Sa?void 0:Sa.commandMetadata)||
void 0===Xa?void 0:Xa.webCommandMetadata)||void 0===kc?void 0:kc.url),!Qc)?null:Qe&&(ue||Qc)?{subscribed:Yb.subscribed,subscribeText:Qe,subscribeCount:mf,unsubscribeText:ue,unsubscribeCount:Uf,enabled:Yb.enabled,signinUrl:Qc,classic:Oa.useClassicSubscribeButton}:null}
function e(Oa){if(Oa){var Sa=[],Xa=Oa.videoId;Xa&&Sa.push("v="+Xa);(Xa=Oa.playlistId)&&Sa.push("list="+Xa);(Oa=Oa.startTimeSeconds)&&Sa.push("t="+Oa);return"/watch?"+Sa.join("&")}}
function f(Oa){if(!Oa)return null;var Sa=Oa.simpleText;return Sa?Sa:Oa.runs?g.Oc(Oa.runs,function(Xa){return Xa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,w=null,y=!1,x=null,B=null,E=null,G=null,K=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(y=g.Nb(l,"browseEndpoint","browseId"))w=y,m="/channel/"+w;n=!1;p="new";(y=!!b.isSubscribe)?x=d(b):B=f(b.subscribersText)}else"WEBSITE"===
h?((E=g.Nb(l,"urlEndpoint","url"))&&(m=E),n=!0,p="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(K=f(b.additionalFeesText)),(n=g.Nb(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=g.Nb(b,"title","accessibility","accessibilityData","label");var H=b.endpoint?b.endpoint.clickTrackingParams:null,ya="";if(b.metadata){var ia=f(b.metadata);ia&&(ya=ia)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ya,callToAction:f(b.callToAction),
LC:b.image,iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:w,subscribeButton:x,subscribersText:B,isSubscribe:y,targetUrl:m||null,nL:n,Bd:H?{itct:H}:null,kS:p,Jp:a?a:null,qL:b.isPlaceholder,impressionUrls:A2(b.impressionUrls||[],z2),fL:A2(b.hovercardShowUrls||[],z2),clickUrls:A2(l.loggingUrls||[],z2),visualElement:g.Lt(b.trackingParams),
productPrice:G,additionalFeesText:K}},B2=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:A2(a.impressionUrls||[],z2),elements:A2(a.elements||[],function(d,e){return xDa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Lt(a.trackingParams));return c},C2=function(a){g.IS.call(this,a);
this.C=this.endscreen=null;this.u={};this.F={};this.D=this.B=null;this.K=[];this.P=!0;this.I=0;a=a.T();this.R=g.nD(a)||g.pD(a);this.events=new g.sR(this);g.D(this,this.events);this.events.N(this.player,g.hF("creatorendscreen"),this.YL);this.events.N(this.player,g.iF("creatorendscreen"),this.ZL);this.events.N(this.player,"resize",this.Va);this.events.N(window,"focus",this.iR);this.load();var b=g.Fe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.eg(this,function(){g.Je(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},yDa=function(a){return a.player.getVideoData().sc?"current":a.R?"new":"current"},D2=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},zDa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",ag:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=B2(f,yDa(a))));E2(a,f)},
ti:{v:c},withCredentials:!0};a.R&&(c.ti.ptype="embedded");var d=b.At;d&&(c.uc={ad_tracking:d});if(b=g.gJ(b))if(b=g.Jc(b),b=g.Fc(b))a.C=g.qq(b,c)},E2=function(a,b,c){c=void 0===c?!0:c;
g.VT(a.player,"creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.q(Object.values(a.u)),e=d.next();!e.done;e=d.next())e.value.dispose();a.u={};a.F={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&ADa(a);c=[];d=new g.eF(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().u||(a.B=new g.V({G:"div",L:"ytp-ce-shadow"}),g.AP(a.player,a.B.element,4),a.D=new g.lO(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=BDa(a,e);if(f){a.u[e.id]=f;a.F[e.id]=e;g.AP(a.player,f.element,4);var h=new g.eF(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);CDa(a,f,e)}else g.Is(new g.tr("buildEndscreenElement null",
e))}g.yN(a.player,c);a.Va()}},ADa=function(a){var b=g.Pt(),c=g.Rt();
c&&b&&a.endscreen.visualElement&&g.du(c,b,a.endscreen.visualElement)},BDa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.aa("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={G:"div",la:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.Jp||"","aria-hidden":"true"},S:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",U:F2(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",U:{href:G2(a,b.targetUrl),tabindex:"-1"},S:[{G:"div",la:["ytp-ce-video-title"].concat(g.ma(c)),U:{dir:g.Bn(b.title||
"")},Z:b.title},{G:"div",L:"ytp-ce-video-duration",Z:b.videoDuration||void 0}]}]};c=new g.V(c);break;case "PLAYLIST":c=a.player.aa("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={G:"div",la:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.Jp||"","aria-hidden":"true"},S:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",U:F2(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",U:{href:G2(a,
b.targetUrl),tabindex:"-1"},S:[{G:"div",la:["ytp-ce-playlist-title"].concat(g.ma(c)),U:{dir:g.Bn(b.title||"")},Z:b.title},{G:"div",L:"ytp-ce-playlist-count",S:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",Z:b.playlistLength||void 0}]}]}]};c=new g.V(c);break;case "CHANNEL":c={G:"div",la:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.Jp||"","aria-hidden":"true"},S:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",S:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",S:[{G:"div",L:"ytp-ce-expanding-overlay-body",S:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{G:"a",la:["ytp-ce-channel-title","ytp-ce-link"],U:{href:G2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Bn(b.title||"")},Z:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",S:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",Z:b.subscribersText}:"",b.metadata?{G:"div",la:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],Z:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",U:F2(b)}]};c=new g.V(c);var d=g.qe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.T().u){var e=null;var f=b.Bd.itct}else e="endscreen",f=null;e=new g.hV(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":c={G:"div",la:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.Jp||"","aria-hidden":"true"},S:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",S:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",S:[{G:"div",L:"ytp-ce-expanding-overlay-body",S:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{G:"div",L:"ytp-ce-website-title",U:{dir:g.Bn(b.title||"")},Z:b.title},{G:"div",L:"ytp-ce-website-metadata",Z:b.metadata},{G:"a",la:["ytp-ce-website-goto","ytp-ce-link"],U:{href:G2(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",U:F2(b)},{G:"div",
L:"ytp-ce-expanding-icon",U:DDa(b.iconUrl)}]};c=new g.V(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",S:[{G:"div",L:"ytp-ce-merchandise-price",Z:b.productPrice}]},b.additionalFeesText&&c.S.push({G:"div",L:"ytp-ce-merchandise-additional-fees",Z:b.additionalFeesText})),c={G:"div",la:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.Jp||"","aria-hidden":"true"},S:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
S:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",S:[{G:"div",L:"ytp-ce-expanding-overlay-body",S:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{G:"div",L:"ytp-ce-merchandise-title",U:{dir:g.Bn(b.title||"")},Z:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",Z:b.metadata},{G:"a",la:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:G2(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",U:F2(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",S:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",Z:b.callToAction||void 0}]}]},c=new g.V(c)}b.qL&&g.I(c.element,"ytp-ce-placeholder");return c},F2=function(a){if(a.LC)var b=a.LC.thumbnails;
return DDa(b?b[b.length-1].url:null)},DDa=function(a){return a?{style:"background-image: url("+a+")"}:{}},CDa=function(a,b,c){function d(m){m&&(b.wa("blur",function(){"none"!=m.style.display&&a.P&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.I(b.element,"ytp-ce-force-expand"),H2(a,c.id,!0)):(g.sn(b.element,"ytp-ce-force-expand"),g.sn(b.element,"ytp-ce-element-hover"),H2(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.wa("mouseenter",function(){I2(a,b,c)});
b.wa("mouseleave",function(){J2(a,b,c)});
a.player.T().u||b.wa("click",function(){g.I(b.element,"ytp-ce-element-hover")});
b.wa("click",function(m){EDa(a,c,m)});
b.wa("keypress",function(m){EDa(a,c,m)});
b.wa("focus",function(){I2(a,b,c)});
b.wa("blur",function(){J2(a,b,c)});
b.wa("touchstart",function(){I2(a,b,c)});
var l=g.se("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.sn(b.element,"ytp-ce-element-hover");g.sn(b.element,"ytp-ce-force-expand")});
b.wa("keydown",function(m){a.P=9===m.keyCode&&!m.shiftKey});
d(g.se("ytp-sb-subscribe",b.element));d(g.se("ytp-sb-unsubscribe",b.element));b.wa("focus",f);b.wa("blur",h)},EDa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.qn(d,"ytp-ce-element");){g.qn(d,"subscribe-label")&&K2(a,b);
if(g.qn(d,"ytp-ce-channel-subscribe"))return;d=g.Le(d)}if(!d||g.qn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.u[b.id])J2(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.kS)K2(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Jc(G2(a,b.targetUrl)),c=g.Fc(c),g.RL(c,void 0,b.Bd);else{var e=a.player.getVideoData().sc,f=function(){var h=G2(a,b.targetUrl),l=b.Bd,m=g.Zp(h);e&&m&&(m.v||m.list)?g.FT(a.player,m.v,l,m.list,!1):g.QL(h,l)};
K2(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},G2=function(a,b){var c=a.player.T();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.TD(c)+b}else return"";return b},I2=function(a,b,c){g.qn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.I(b.element,"ytp-ce-element-hover"):a.player.T().u?(new g.F(function(){g.I(b.element,"ytp-ce-element-hover")},200)).start():g.I(b.element,"ytp-ce-element-hover"),L2(a,c.fL),H2(a,c.id,!0))},J2=function(a,b,c){g.sn(b.element,"ytp-ce-element-hover");
g.sn(b.element,"ytp-ce-force-expand");H2(a,c.id,!1)},H2=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.q(Object.keys(a.u)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.J(a.u[e].element,"ytp-ce-element-shadow-show",c)},L2=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||D2(a))c&&c();else{b=FDa(a,b);var e=0,f=!1,h=new g.F(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.pu(b[a],d)}},K2=function(a,b,c){L2(a,b.clickUrls,c);
(a=g.Rt())&&b.nL&&g.gu(a,b.visualElement)},FDa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(GDa(b[e],c));return d},GDa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},HDa=function(a){return Array.isArray(a)&&a.length?a[0]:a},M2=function(a){return"string"===typeof a?a:""},N2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},IDa=function(a){this.externalId=a},JDa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.u=d},O2=function(a){return a.value?a.value:null},P2=function(a){if(!a)return null;
var b=g.Jc(M2(a.value));b=g.Fc(b);if(!b)return null;var c=N2(a.target,KDa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new JDa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},LDa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},ODa=function(a){if(!a)return null;
var b=N2(a.type,MDa),c=N2(a.trigger,NDa),d=HDa(a.url);d=P2(d?d:null);a=HDa(a.subscribeData);var e=a?a:null;e?(a=M2(e.external_user_id),e=M2(e.subscription_token),a=a&&e?new IDa(a):null):a=null;return b?new LDa(b,c,d,a):null},Q2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},PDa=function(a,b){return g.fb(a.action,b,void 0)},QDa=function(a,b){this.context=a;
this.u=b},S2=function(a){return a.customMessage?R2("div","iv-card-message",a.customMessage):""},T2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{G:"div",L:"iv-card-image",U:{style:c},S:d}},U2=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(R2("li","",c.value));return{G:"ul",L:"iv-card-meta-info",S:b}},R2=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Bn(c);return{G:a,U:b,Z:c}},RDa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Ys&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Ys+");");c.dir=g.Bn(a.customMessage);var d=[{G:"span",Z:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",la:b,U:c,S:d}},V2=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.u(e.value,d,c.id,c.Bd,c.Tf.click,5)}},SDa=function(a,b){this.merchant=a;
this.price=b},TDa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},UDa=function(a,b){return b?b:TDa(a)?"current":"new"},W2=function(a,b){g.C.call(this);
var c=this;this.element=a;this.context=b;this.Ta=!1;this.Aa=new Map;this.Ja=new Map;this.context.J.addEventListener(g.hF("annotations_module"),function(d){(d=c.Aa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.iF("annotations_module"),function(d){(d=c.Ja.get(d))&&d.apply(c)})},X2=function(a,b,c,d,e,f,h){a.context.u.wa(b,"click",function(l){a.nz(c,d,e,f||[],h||0,l)});
a.context.u.wa(b,"touchstart",function(){a.Ta=!1});
a.context.u.wa(b,"touchmove",function(){a.Ta=!0})},VDa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},Y2=function(a,b,c){return{ND:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
QH:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
nw:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},a3=function(a,b,c){W2.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.ka=this.ub=this.C=this.Zd=!1;this.ma=null;this.cards=[];this.Ya=this.R=this.ha=this.F=this.za=this.u=null;this.X=[];this.K=this.Nd=this.fa=null;this.I=0;this.ba=new g.F(g.Ka,c.W.Pe?4E3:3E3);g.D(this,this.ba);this.Qa=new g.F(g.Ka);g.D(this,this.Qa);this.Y=new QDa(c,function(e,f,h,l,m,n){X2(d,e,f,h,l,m,n)});
this.P=new g.V({G:"div",L:"iv-drawer",U:{id:"iv-drawer"},S:[{G:"div",L:"iv-drawer-header",U:{"aria-role":"heading"},S:[{G:"span",L:"iv-drawer-header-text"},{G:"button",la:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.D(this,this.P);this.D=this.P.element;this.Ga=new g.lO(this.P,330);g.D(this,this.Ga);this.kb=g.se("iv-drawer-header-text",this.D);this.B=g.se("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.ub&&Z2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.ub=d.C)&&$2(d)})},WDa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){Z2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){$2(a)});
var d=c.headerText;g.Ne(a.kb,d);a.R&&a.R.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.fa=g.Lt(c.trackingParams);a.K=g.Lt(c.closeTrackingParams);a.Nd=g.Lt(c.iconTrackingParams)},XDa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"simple",teaserText:g.T(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bd:b3(a,c,b,d),sponsored:!1,Tf:Y2(d,e,d.command),Bj:d.trackingParams?g.Lt(d.trackingParams):null,mh:e.trackingParams?g.Lt(e.trackingParams):
null,Nd:f&&f.trackingParams?g.Lt(f.trackingParams):null,imageUrl:c3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.T(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Ys:null,title:d.title?g.T(d.title):"",customMessage:d.callToAction?g.T(d.callToAction):"",url:d.command.urlEndpoint.url?P2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};d3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"collaborator",teaserText:g.T(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bd:b3(a,c,b,d),sponsored:!1,Tf:Y2(d,e,d.endpoint),Bj:d.trackingParams?g.Lt(d.trackingParams):null,mh:e.trackingParams?g.Lt(e.trackingParams):null,Nd:f&&f.trackingParams?g.Lt(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.T(d.customText):null,OG:c3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.T(d.channelName):"",metaInfo:[d.subscriberCountText?g.T(d.subscriberCountText):""],url:P2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};d3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"playlist",teaserText:g.T(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bd:b3(a,c,b,d),sponsored:!1,Tf:Y2(d,e,d.action),Bj:d.trackingParams?g.Lt(d.trackingParams):null,mh:e.trackingParams?g.Lt(e.trackingParams):null,Nd:f&&f.trackingParams?g.Lt(f.trackingParams):
null,qs:c3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.T(d.customMessage):null,playlistVideoCount:g.T(d.playlistVideoCount),title:d.playlistTitle?g.T(d.playlistTitle):"",metaInfo:[d.channelName?g.T(d.channelName):"",d.videoCountText?g.T(d.videoCountText):""],url:P2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:VDa(d.action)})};d3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"video",teaserText:g.T(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bd:b3(a,c,b,d),sponsored:!1,Tf:Y2(d,e,d.action),Bj:d.trackingParams?g.Lt(d.trackingParams):null,mh:e.trackingParams?g.Lt(e.trackingParams):null,Nd:f&&f.trackingParams?g.Lt(f.trackingParams):null,qs:c3(d.videoThumbnail.thumbnails,258).url,
videoDuration:d.lengthString?g.T(d.lengthString):null,customMessage:d.customMessage?g.T(d.customMessage):null,title:d.videoTitle?g.T(d.videoTitle):"",metaInfo:[d.channelName?g.T(d.channelName):"",d.viewCountText?g.T(d.viewCountText):""],isLiveNow:!!d.badge,url:P2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:VDa(d.action)})};d3(a,c)}a.I++},c3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},b3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},ZDa=function(a,b){var c=YDa(a,b);
c&&(c===a.u&&(a.u=null),a.J.removeCueRange(c.card.id),g.Je(c.rx),g.ob(a.cards,c),a.ct(),e3(a))},Z2=function(a,b,c){if(!a.C){a.Ga.show();
a.za=new g.F(function(){g.I(a.context.J.getRootNode(),g.YY.IV_DRAWER_OPEN)},0);
a.za.start();a.ma=g.cp(a.B,"mousewheel",function(h){a.ba.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.Rt();d&&a.fa&&a.K&&g.eu(d,[a.fa,a.K]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.uE||(f.uE=!0,$Da(a.context.logger,f.card.Tf.ND,b)),d&&g.eu(d,[f.card.Bj]);r2(a.J);c&&(a.F=new g.F(function(){a.ha=a.R;a.Ya.focus()},330),a.F.start())}},$2=function(a){a.C&&(a.Ga.hide(),g.dp(a.ma),a.ma=null,g.sn(a.context.J.getRootNode(),g.YY.IV_DRAWER_OPEN),a.C=!1,r2(a.J),a.F&&a.F.stop(),a.F=new g.F(function(){a.ha&&(a.ha.focus(),a.ha=null)},330),a.F.start())},bEa=
function(a){g.rn(a.Pa(),[g.YY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.AP(a.J,a.D,5);aEa(a);a.R=g.se("ytp-cards-button",a.J.getRootNode());a.Ya=g.se("iv-drawer-close-button",a.D);a.Zd=!0},aEa=function(a){var b=g.se("iv-drawer-close-button",a.D);
a.context.u.wa(b,"click",a.JJ,a);a.context.u.wa(a.B,"touchend",function(){a.ba.start()});
a.context.u.wa(a.B,"scroll",a.YJ,a);a.context.B.subscribe("onHideControls",function(){a.ka=!0});
a.context.B.subscribe("onShowControls",function(){a.ka=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.ka=g.qn(a.J.getRootNode(),"ytp-autohide")});
a.X.push(g.No("iv-button-shown",a.vL,a));a.X.push(g.No("iv-button-hidden",a.uL,a));a.X.push(g.No("iv-teaser-shown",a.sM,a));a.X.push(g.No("iv-teaser-hidden",a.xL,a));a.X.push(g.No("iv-teaser-clicked",a.rM,a))},d3=function(a,b){a.Zd||bEa(a);
ZDa(a,b.id);var c=cEa(a,b);if(c){var d={card:b,rx:c.element,uE:!1},e=dEa(a,d);g.ub(a.cards,e,0,d);c.ga(a.B,e);a.ct();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.u=d,e3(a),eEa(a,d),Z2(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&fEa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){fEa(a,d)}),e3(a))}},cEa=function(a,b){switch(b.type){case "simple":var c=a.Y;
var d=b.displayDomain?{G:"div",L:"iv-card-image-text",Z:b.displayDomain}:void 0;var e=RDa(b);d={G:"div",la:["iv-card"],S:[{G:"a",L:"iv-click-target",U:{href:b.url?O2(b.url)||"":""},S:[T2(b.imageUrl,d),{G:"div",L:"iv-card-content",S:[R2("h2",void 0,b.title),e]}]}]};d=new g.V(d);V2(c,g.re("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.Y,d={G:"div",la:["iv-card","iv-card-channel"],S:[{G:"a",la:["iv-click-target"],U:{href:O2(b.url)||"","data-ytid":b.channelId},S:[T2(b.OG),
{G:"div",L:"iv-card-content",S:[S2(b),{G:"h2",L:"iv-card-primary-link",Z:b.title},U2(b)]}]}]},d=new g.V(d),V2(c,g.re("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.Y,d={G:"div",la:["iv-card","iv-card-playlist"],S:[{G:"a",L:"iv-click-target",U:{href:O2(b.url)||""},S:[T2(b.qs,{G:"div",L:"iv-card-image-overlay",S:[{G:"span",L:"iv-card-playlist-video-count",Z:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",S:[S2(b),R2("h2","iv-card-primary-link",b.title),U2(b)]}]}]},d=new g.V(d),
V2(c,g.re("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.Y;var f=!g.kb(b.offers);d=["iv-card"];e="";var h=RDa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({G:"div",L:"iv-card-offer-price",Z:h.price}),h.merchant&&f.push({G:"div",L:"iv-card-offer-merchant",Z:h.merchant}),h={G:"div",S:f});f=b.url?O2(b.url)||"":"";d={G:"div",la:d,U:{tabindex:"0"},S:[{G:"a",la:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",S:[b.sponsored?{G:"div",L:"iv-card-sponsored",S:["Sponsored",{G:"div",L:"iv-ad-info-container",S:[{G:"div",L:"iv-ad-info",Z:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",S:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",U:{href:f},S:[R2("h2",e,b.title),h]}]}]};d=new g.V(d);e=g.Fe("span");g.Ne(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Hc(e,"adInfo");V2(c,g.re("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.Y,d=b.isLiveNow?{G:"span",la:["yt-badge","yt-badge-live"],Z:"LIVE NOW"}:null,d={G:"div",la:["iv-card","iv-card-video"],S:[{G:"a",L:"iv-click-target",U:{href:O2(b.url)||""},S:[T2(b.qs,b.videoDuration?{G:"span",L:"iv-card-video-duration",Z:b.videoDuration}:void 0),{G:"div",L:"iv-card-content",S:[S2(b),R2("h2","iv-card-primary-link",b.title),U2(b),d]}]}]},d=new g.V(d),V2(c,g.re("iv-click-target",d.element),
b,b.url),d;default:return null}},dEa=function(a,b){if(0===a.cards.length)return 0;
var c=g.gb(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},gEa=function(a){return a.u?"productListing"===a.u.card.type:g.qh(a.cards,function(b){return"productListing"===b.card.type})},e3=function(a){g.J(a.J.getRootNode(),"ytp-cards-shopping-active",gEa(a))},fEa=function(a,b){if(!g.qn(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.u!==b){var c=g.Rt(),d=a.u?a.u.card.Nd:a.Nd;
c&&d&&g.fu(c,[d]);a.u=b;e3(a)}if(c="none"!=a.Pa().style.display)2===a.context.J.getPresentingPlayerType()?c=1===a.context.J.getAdState():(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=1===c||3===c||d);c&&b.card.teaserDurationMs&&(c={teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs},(d=g.QT(g.GT(a.J)))&&d.jz(!0,c));a.Qa.isActive()||((!a.C||!a.ba.isActive()&&a.ka)&&eEa(a,b),a.Qa.start(910+b.card.teaserDurationMs))}},eEa=function(a,b){if(a.P.fb){var c=new v2([0,
a.B.scrollTop],[0,b.rx.offsetTop],600,rDa);a.context.C.wa(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.C.wa(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.IN(a.P,!0),a.B.scrollTop=b.rx.offsetTop,g.IN(a.P,!1)},f3=function(a){return a.u&&a.u.card?a.u.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},YDa=function(a,b){return g.fb(a.cards,function(c){return c.card.id===b})},g3=function(a,b,c){W2.call(this,a,b);
this.annotation=c;this.isActive=!1},hEa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},h3=function(a,b,c){g3.call(this,a,b,c);
this.B=null;this.K=!1;this.C=null;this.D=!1;this.u=this.I=this.F=null},iEa=function(a,b){var c=void 0===c?0:c;
var d=pDa(b).width;g.Cg(b,d);c=new x2(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,qDa);g.D(a,c);a.context.C.wa(c,"begin",function(){g.Mg(b,!0)});
c.play()},lEa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
la:["iv-branding-context-name"],Z:b.channel_name}),d=a.createElement({G:"div",la:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.u=new g.hV(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.J),a.u.ga(d));var f=a.createElement({G:"div",la:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",la:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Mg(h,!1);var l=a.createElement({G:"div",la:["branding-context-container-outer"]});l.appendChild(h);g.ug(l,"right",b.image_width+"px");a.Pa().appendChild(l);a.C=new g.F(function(){jEa(a,h,l)},500);
g.D(a,a.C);a.context.u.wa(a.Pa(),"mouseover",function(){kEa(a,h,l,f,b.image_height)});
a.context.u.wa(a.Pa(),"mouseout",function(){a.C.start()})}},kEa=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Lg(b);a.u||(b.style.width=g.Bg(f.width,!0),c.style.width=g.Bg(f.width,!0));g.ug(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.ug(d,"right","1px");a.D=!0;g.Mg(b,!0);a.F=new g.F(function(){g.I(this.Pa(),"iv-branding-active")},0,a);
a.F.start()}},jEa=function(a,b,c){g.sn(a.Pa(),"iv-branding-active");
a.I=new g.F(function(){g.Mg(b,!1);a.u||(c.style.width=g.Bg(0,!0))},250);
a.I.start();a.D=!1},mEa=function(a,b,c,d,e,f,h){this.u=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},i3=function(a,b,c){g3.call(this,a,b,c);
var d=this;this.R=this.isCollapsed=this.P=!1;this.I=5E3;this.B=this.C=this.u=this.D=null;this.K=this.createElement({G:"div",la:["iv-promo-contents"]});this.F=new g.F(function(){d.u.setAttribute("aria-hidden","true");g.Mg(d.C,!1);g.Mg(d.B,!0)},700,this);
g.D(this,this.F)},nEa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.Pa().setAttribute("aria-hidden","true");a.Pa().setAttribute("aria-label","Promotion");a.Pa().tabIndex=0;var e=a.annotation.Md(),f=b.image_url;if(f){var h=a.createElement({G:"div",la:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",L:"iv-promo-video-duration",Z:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",Z:b.playlist_length.toString()}),h.appendChild(f));e&&X2(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.jd(f,O2(e)),a.u=f):a.u=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",S:[{G:"strong",Z:b.text_line_1}]});
var m=a.createElement({G:"p",S:[{G:"span",L:"iv-promo-link",Z:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",la:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",la:["iv-button","iv-promo-button"],S:[{G:"span",L:"iv-button-content",Z:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&X2(a,a.Pa(),e,a.annotation.id,b.session_data,void 0,c)}g.I(a.u,"iv-click-target");
e&&X2(a,a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",S:[{G:"span",Z:b.text_line_1}]}),m=a.createElement({G:"p",S:[{G:"strong",Z:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",la:["yt-badge","iv-promo-badge-live"],Z:"LIVE NOW"})),g.I(a.u,"iv-click-target"),e&&X2(a,a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.K.appendChild(a.u);p&&a.K.appendChild(p);c=
a.createElement({G:"div",L:"iv-promo-actions"});a.B=a.createElement({G:"button",la:["iv-promo-expand","ytp-button"]});a.B.title="Expand";a.context.u.wa(a.B,"click",function(r){j3(a,5E3,r)});
c.appendChild(a.B);g.Mg(a.B,!1);a.context.u.wa(a.Pa(),"mouseover",a.NK,a);a.context.u.wa(a.Pa(),"mouseout",a.MK,a);a.context.u.wa(a.Pa(),"touchend",function(r){j3(a,5E3,r)});
a.C=a.createElement({G:"button",la:["iv-promo-close","ytp-button"]});a.C.title="Close";a.context.u.wa(a.C,"click","cta"===a.annotation.style&&b.text_line_3?a.HK:a.GK,a);c.appendChild(a.C);g.rn(a.Pa(),d);h&&(a.Pa().appendChild(h),n&&h.appendChild(n));a.Pa().appendChild(a.K);a.Pa().appendChild(c)},j3=function(a,b,c){c.stopPropagation();
oEa(a);pEa(a,b);a.u.focus()},qEa=function(a){a.isCollapsed||a.R||a.D||(g.I(a.Pa(),"iv-promo-collapsed"),a.isCollapsed=!0,a.F.start())},oEa=function(a){a.F.stop();
a.isCollapsed&&(g.tn(a.Pa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Mg(a.B,!1),g.Mg(a.C,!0))},pEa=function(a,b){a.D||(a.D=g.Lm(function(){k3(this);
qEa(this)},b,a))},k3=function(a){a.D&&(g.v.clearTimeout(a.D),a.D=null)},rEa=function(a){this.J=a},$Da=function(a,b,c){b&&(c?l3(a,b.map(function(d){return g.en(d,c)})):l3(a,b))},l3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.pu(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},m3=function(a){g.IS.call(this,a);
var b=this;this.P=!1;this.loadNumber=0;this.K={};this.logger=new rEa(this.player);this.F=new g.sR(this);this.I=this.C=null;this.events=new g.sR(this);this.R=this.u=null;this.X=[];g.D(this,this.F);this.F.N(this.player,"onVideoAreaChange",function(){b.V("onVideoAreaChange")});
this.F.N(this.player,"onHideControls",function(){b.V("onHideControls")});
this.F.N(this.player,"onShowControls",function(){b.V("onShowControls")});
this.F.N(this.player,"resize",function(d){b.V("resize",d)});
this.F.N(this.player,"presentingplayerstatechange",function(d){b.V("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.qM,this);this.subscribe("resize",this.Av,this);this.player.T().K.subscribe("vast_info_card_add",this.vG,this);g.D(this,this.events);this.Y=this.createElement({G:"div",L:"video-custom-annotations"});this.B=new g.V({G:"div",la:["ytp-player-content","ytp-iv-player-content"]});g.D(this,this.B);g.AP(this.player,this.B.element,4);this.B.hide();this.D=new g.V({G:"div",la:["ytp-iv-video-content"]});g.D(this,this.D);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Y);this.D.element.appendChild(a);sEa(this)&&this.load();var c=this.createElement({G:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.eg(this,function(){g.Je(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},tEa=function(a){a=a.createElement({G:"div",
la:["annotation","annotation-type-custom"]});g.Mg(a,!1);return a},sEa=function(a){var b=a.player.T();
a=a.player.getVideoData();return a.sc&&b.pfpChazalUi?!1:1===(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.wI||b.K.get(a.videoId)||g.iJ(a)||g.jJ(a)?!0:!1},uEa=function(a,b){var c=!b.isCued()&&!g.U(b,1024);
g.IN(a.B,c);g.IN(a.D,c)},vEa=function(a,b,c){a.P=!0;
a.I=g.qq(b,c)},wEa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(wEa(a,e))}return c},zEa=function(a){var b=a.player.getVideoData();
if(b.Ng){var c=a.player.T().K.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.kq(h)&&h.responseXML?h.responseXML:null)&&n3(a,h)}};
g.up()&&(d.onFinish=xEa(a,d.onFinish));d.postParams={ic_only:"1"};yEa(d,c);a.P=!0;g.qq(b.Ng,d)}}},yEa=function(a,b){a.method="POST";
a.uc=a.uc||{};b.Wp&&(a.uc.ic_coll=b.Wp);b.jt&&(a.uc.ic_xml=b.jt);b.ws&&(a.uc.ic_track=b.ws)},AEa=function(a){var b=new g.V({G:"div"});
g.Mg(b.element,!1);var c=new a3(a.player,b.element,o3(a));g.D(c,b);b.ga(a.B.element);c.Ur();return c},o3=function(a){if(!a.R){var b=new y2(a);
g.D(a,b);var c=new g.f1(a);g.D(a,c);a.R=new mEa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.za)}return a.R},n3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Rt();if(e){var f=g.Pt();f&&g.Xt(g.vo("use_default_events_client")?void 0:g.Cs,e,f,[g.Lt(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=wEa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=N2(h.type,BEa),r=N2(h.style,CEa),t=M2(h.data),w=0!==t.length?JSON.parse(t):{};var y=h.action;h=ODa;if(null==y)var x=null;else if(g.Na(y)){m=[];for(var B=g.q(y),E=B.next();!E.done;E=
B.next()){var G=h(E.value);G&&m.push(G)}x=m}else{var K=h(y);x=K?[K]:[]}f=n&&p?new Q2(n,p,r,x,w):null}else f=null}catch(Xa){}if(f)if("branding"===f.type||"promotion"===f.type){h=a;m=f;var H=tEa(h),ya=null;switch(m.type){case "branding":if(h.player.T().Nb)break;h.B.element.appendChild(H);ya=new h3(H,o3(h),m);break;case "promotion":g.AP(h.player,H,4),ya=new i3(H,o3(h),m)}ya&&ya.Ur();if(h=ya)g.D(a,h),a.K[f.id]=h}else if("card"===f.type||"drawer"===f.type){a.u||(a.u=AEa(a),g.D(a,a.u));if("card"===f.type){c=
a.u;var ia=f&&f.data&&f.data.card_type;h=f.data;if(ia)switch(m=h.tracking||{},m={ND:m.impression,click:m.click,close:m.close,QH:m.teaser_impression,nw:m.teaser_click},H=h.tracking_params||{},ya=null,ia){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,Tf:m,Bj:H.card?g.Lt(H.card):null,mh:H.teaser?g.Lt(H.teaser):null,Nd:H.icon?
g.Lt(H.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,OG:h.image_url,title:h.title,metaInfo:h.meta_info,url:P2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};d3(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,Tf:m,Bj:H.card?g.Lt(H.card):null,
mh:H.teaser?g.Lt(H.teaser):null,Nd:H.icon?g.Lt(H.icon):null,qs:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:P2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};d3(c,f);break;case "productListing":h.signin_url&&(ya=P2({target:"current",value:h.signin_url}));ia=[];for(var Oa=h.offers||[],Sa=0;Sa<Oa.length;Sa++)ia.push(new SDa(g.pd(Oa[Sa].merchant),g.pd(Oa[Sa].price)));
f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,Tf:m,Bj:H.card?g.Lt(H.card):null,mh:H.teaser?g.Lt(H.teaser):null,Nd:H.icon?g.Lt(H.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Ys:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:P2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),v5:ya,u5:h.signin_title?h.signin_title:void 0,t5:h.signin_message?h.signin_message:void 0,offers:ia};d3(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,Tf:m,Bj:H.card?g.Lt(H.card):null,mh:H.teaser?g.Lt(H.teaser):null,Nd:H.icon?
g.Lt(H.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Ys:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:P2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};d3(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,Tf:m,Bj:H.card?g.Lt(H.card):null,mh:H.teaser?g.Lt(H.teaser):null,Nd:H.icon?g.Lt(H.icon):null,qs:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:P2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},d3(c,f)}}else WDa(a.u,f);c=!0}}c&&(r2(a.player),a.Av())},DEa=function(a,b){var c=!1;
a.u||(a.u=AEa(a),g.D(a,a.u));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(XDa(a.u,e.cardRenderer),c=!0);c&&(c=a.u,d=b.headerText?g.T(b.headerText):"",g.Ne(c.kb,d),c.R&&c.R.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.fa=b.trackingParams?g.Lt(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.Lt(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Nd=b.icon.infoCardIconRenderer.trackingParams?
g.Lt(b.icon.infoCardIconRenderer.trackingParams):null,r2(a.player),a.Av())},EEa=function(a,b,c,d,e){if(!a.player.T().Nb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new LDa("openUrl","click",new JDa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.T(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.T(b.subscriberCountText))):(b.subscriberCountText&&(e=g.T(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.T(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.T(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.T(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new Q2(c,"branding","branding",f,d);l=tEa(a);a.B.element.appendChild(l);f=new h3(l,o3(a),f);f.Ur();g.D(f,f);a.K[c]=f}},xEa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.na()||(d.unshift(b),b=g.Ta.apply(window,d),a.X.push(g.sp(b)))}},FEa=function(a){return"annotation-editor"===a||"live-dashboard"===a},s2={},t2=null;g.Va(v2,g.vn);g.k=v2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Ka)this.progress=0,this.coords=this.u;else if(this.Hb())return!1;u2(this);this.startTime=a=g.A();-1==this.Ka&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.xv();this.Qg("play");-1==this.Ka&&this.Qg("resume");this.Ka=1;var b=g.Ra(this);b in s2||(s2[b]=this);tDa();uDa(this,a);return!0};
g.k.stop=function(a){u2(this);this.Ka=0;a&&(this.progress=1);vDa(this,this.progress);this.Qg("stop");this.ur()};
g.k.pause=function(){this.Hb()&&(u2(this),this.Ka=-1,this.Qg("pause"))};
g.k.ca=function(){0==this.Ka||this.stop(!1);this.Qg("destroy");v2.Kd.ca.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.oy=function(){this.Qg("animate")};
g.k.Qg=function(a){this.dispatchEvent(new wDa(a,this))};
g.Va(wDa,g.El);g.Va(w2,v2);w2.prototype.C=g.Ka;w2.prototype.oy=function(){this.C();w2.Kd.oy.call(this)};
w2.prototype.ur=function(){this.C();w2.Kd.ur.call(this)};
w2.prototype.xv=function(){this.C();w2.Kd.xv.call(this)};
g.Va(x2,w2);x2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.u(y2,g.C);y2.prototype.wa=function(a,b,c,d){c=(0,g.z)(c,d||this.B);a=g.cp(a,b,c);this.u.push(a);return a};
y2.prototype.Cu=function(a,b,c,d){c=(0,g.z)(c,d||this.B);a=g.mp(a,b,c);this.u.push(a);return a};
y2.prototype.Mb=function(a){g.dp(a);g.ob(this.u,a)};
y2.prototype.ca=function(){g.dp(this.u);this.u.length=0;g.C.prototype.ca.call(this)};g.u(C2,g.IS);g.k=C2.prototype;g.k.load=function(){g.IS.prototype.load.call(this);if(!D2(this)){var a=g.hJ(this.player.getVideoData());a?(a=B2(a,yDa(this)),E2(this,a,!1)):zDa(this)}};
g.k.unload=function(){E2(this,null);this.C&&(this.C.abort(),this.C=null);g.IS.prototype.unload.call(this)};
g.k.Be=function(a,b){if(!D2(this))return null;if("loadCustomEndscreenRenderer"===a){var c=B2(b,"new");E2(this,c);return!0}return null};
g.k.getOptions=function(){return D2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Va=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<GEa.length;f++){var h=Math.abs(b.width-GEa[f]);if(-1===e||d>=h)e=f,d=h}d=HEa[e];this.B&&g.ug(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.u[f],
h=this.F[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Kg(e.element,Math.round(h.width*a.width),f);g.Cg(e.element,m,n);g.tn(e.element,IEa);m=h.left+h.width/2;h=h.top+l/2;g.I(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.tn(e.element,HEa);g.I(e.element,d);(e=g.qe(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.ug(e,"height",f+"px")}}}}};
g.k.YL=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())L2(this,this.endscreen.impressionUrls),(a=g.Rt())&&this.endscreen.visualElement&&g.Yt(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.u[a],c=this.F[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");L2(this,c.impressionUrls);(b=g.Rt())&&g.Yt(b,c.visualElement,void 0);this.player.T().C&&this.player.xa("endscreenelementshown",
a)}};
g.k.ZL=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.u[a];g.sn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.sn(b,"ytp-ce-shown");this.player.T().C&&this.player.xa("endscreenelementhidden",a)}};
g.k.iR=function(a){var b=this;a.target===window&&(new g.F(function(){for(var c=g.q(Object.values(b.u)),d=c.next();!d.done;d=c.next())g.tn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var GEa=[346,426,470,506,570,640,853,1280,1920],HEa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),IEa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var KDa={dW:"current",z0:"new"};var MDa={CLOSE:"close",K0:"openUrl",jJ:"subscribe"},NDa={lU:"click",CLOSE:"close",yX:"hidden",d2:"rollOut",e2:"rollOver",L2:"shown"};Q2.prototype.Md=function(){var a=PDa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var CEa={ET:"anchored",OI:"branding",CHANNEL:"channel",cW:"cta",BX:"highlightText",zY:"label",PLAYLIST:"playlist",C1:"popup",U2:"speech",jJ:"subscribe",r3:"title",VIDEO:"video",y4:"website"},BEa={OI:"branding",aU:"card",rW:"drawer",AX:"highlight",WZ:"marker",K1:"promotion",TEXT:"text",E4:"widget"};g.u(W2,g.C);g.k=W2.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.eF(a,b,{id:c});a.namespace="annotations_module";d&&this.Aa.set(a,d);e&&this.Ja.set(a,e);g.yN(this.context.J,[a])};
g.k.Ur=function(){this.context.B.subscribe("resize",this.ct,this)};
g.k.Pa=function(){return this.element};
g.k.nz=function(a,b,c,d,e,f){if(this.Ta)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Je(this.Pa())};
g.k.ct=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=O2(a);if(f){var h=UDa(f,a.target),l=function(){a.u&&e.context.J.pauseVideo();var m=e.context.videoData.sc||!1,n=g.Zp(f||"");m&&n&&(n.v||n.list)?g.ET(e.context.J.app,n.v,b,n.list,!1,void 0):g.RL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);l3(this.context.logger,c,l,d);TDa(f)||(c=g.Rt(),d=b.itct,c&&d&&g.gu(c,g.Lt(d)))}};
g.k.ca=function(){this.Aa.clear();this.Ja.clear();g.C.prototype.ca.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.D(this,a);return a.element};g.u(a3,W2);g.k=a3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Lg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.ct=function(){var a=this.isAvailable();g.Mg(this.Pa(),a);g.J(this.context.J.getRootNode(),g.YY.IV_DRAWER_ENABLED,a);r2(this.J)};
g.k.destroy=function(){var a=g.QT(g.GT(this.J));a&&a.jz(!1,void 0);try{this.J.getRootNode().removeChild(this.D)}catch(b){}g.Oo(this.X);g.dp(this.ma);this.za&&this.za.dispose();this.F&&this.F.dispose();W2.prototype.destroy.call(this)};
g.k.JJ=function(){if(this.C){l3(this.context.logger,f3(this).Tf.close);var a=g.Rt();a&&this.K&&g.gu(a,this.K);$2(this)}};
g.k.YJ=function(){g.J(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.vL=function(){var a=g.Rt(),b=f3(this);b=b?b.Nd:this.Nd;a&&b&&g.eu(a,[b])};
g.k.uL=function(){var a=g.Rt(),b=f3(this);b=b?b.Nd:this.Nd;a&&b&&g.fu(a,[b])};
g.k.sM=function(){var a=f3(this);l3(this.context.logger,a.Tf.QH);var b=g.Rt();b&&a&&g.eu(b,[a.mh,a.Nd])};
g.k.xL=function(){var a=g.Rt(),b=f3(this);a&&b&&g.fu(a,[b.mh])};
g.k.rM=function(a){var b=f3(this),c=g.Rt();this.u?a?(a=this.context.logger,l3(a,b.Tf.nw),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.mh&&g.gu(c,b.mh)):(a=this.context.logger,l3(a,b.Tf.nw),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Nd&&g.gu(c,b.Nd)):(a=this.context.logger,l3(a,b.Tf.nw),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Nd&&g.gu(c,this.Nd))};g.u(g3,W2);g3.prototype.Ur=function(){W2.prototype.Ur.call(this);hEa(this)};
g3.prototype.show=function(){W2.prototype.show.call(this);var a=g.Rt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.eu(a,[g.Lt(b.itct)])};
g3.prototype.hide=function(){W2.prototype.hide.call(this);var a=g.Rt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.fu(a,[g.Lt(b.itct)])};g.u(h3,g3);
h3.prototype.show=function(){if(!this.isActive){g3.prototype.show.call(this);if(!this.K){g.I(this.Pa(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({G:"img",la:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Mg(this.B,!1);var b=this.createElement({G:"div",la:["branding-img-container"]});b.appendChild(this.B);this.Pa().appendChild(b);(b=this.annotation.Md())&&X2(this,this.B,b,this.annotation.id,a.session_data);
lEa(this,a);this.K=!0}g.Mg(this.Pa(),!0);this.isActive=!0;this.B&&iEa(this,this.B)}};
h3.prototype.hide=function(){this.isActive&&(g3.prototype.hide.call(this),g.Mg(this.Pa(),!1),this.isActive=!1)};
h3.prototype.destroy=function(){this.u&&(this.u.dispose(),this.u=null);g3.prototype.destroy.call(this)};g.u(i3,g3);g.k=i3.prototype;g.k.show=function(){this.isActive||(g3.prototype.show.call(this),this.P||(nEa(this),this.P=!0),g.Mg(this.Pa(),!0),g.Lm(function(){g.sn(this.Pa(),"iv-promo-inactive")},100,this),this.Pa().removeAttribute("aria-hidden"),this.isActive=!0,k3(this),oEa(this),pEa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.I(this.Pa(),"iv-promo-inactive"),this.isActive=!1,this.Pa().setAttribute("aria-hidden","true"))};
g.k.nz=function(a,b,c,d,e,f){return this.isCollapsed?!1:g3.prototype.nz.call(this,a,b,c,d,e,f)};
g.k.NK=function(a){this.R=!0;j3(this,500,a)};
g.k.MK=function(){this.R=!1;qEa(this)};
g.k.GK=function(a){a.stopPropagation();this.hide()};
g.k.HK=function(a){a.stopPropagation();k3(this);this.isCollapsed=!0;g.I(this.Pa(),"iv-promo-collapsed-no-delay");this.F.start()};
g.k.destroy=function(){this.F.dispose();g3.prototype.destroy.call(this)};g.u(m3,g.IS);g.k=m3.prototype;g.k.Be=function(a,b){if(!FEa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.e1(b);c&&n3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.u&&(ZDa(this.u,b),r2(this.player)),!0}return null};
g.k.getOptions=function(){return FEa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Av=function(){if(this.D){var a=g.cG(this.player).getVideoContentRect(!0);g.Kg(this.D.element,a.width,a.height);g.Cg(this.D.element,a.left,a.top)}if(this.u){var b=this.player.Qi();a=this.u;b=b.width;g.J(a.D,"iv-drawer-small",426>=b);g.J(a.D,"iv-drawer-big",1280<=b)}};
g.k.qM=function(a){uEa(this,a.state);g.U(a.state,2)&&(this.Xq()&&this.FE()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.jz(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.I=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.kq(h)&&h.responseXML?h.responseXML:null)&&(n3(b,h),g.I(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.IS.prototype.load.call(this);uEa(this,g.uK(this.player));this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.up()&&(a=xEa(this,a));var e={format:"XML",ag:a,onError:function(){b.I=null},
ti:{}};c.isPharma&&(e.ti.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().K.get(d);f&&yEa(e,f);f=f&&(f.jt||f.Wp);if(!c.Us||f)c.Ng?vEa(this,c.Ng,e):(this.C=function(){b.Ra(e)},this.player.addEventListener("videodatachange",this.C));
g.AP(this.player,this.D.element,4);this.Av();(f=g.iJ(c))&&DEa(this,f);(f=g.jJ(c))&&f.featuredChannel&&EEa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.Ra=function(a){var b=this.player.getVideoData();b.Ng&&(this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null),vEa(this,b.Ng,a))};
g.k.unload=function(){g.VT(this.player,"annotations_module");for(var a=g.q(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.R=null;this.u&&(this.u.destroy(),this.u=null,r2(this.player));this.P=!1;this.I&&(this.I.abort(),this.I=null);this.K={};this.B.hide();g.IS.prototype.unload.call(this);this.D.detach();this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null)};
g.k.vG=function(a){a===this.player.getVideoData().videoId&&(this.loaded?zEa(this):this.load())};
g.k.Xq=function(){return!!this.u&&this.u.isAvailable()};
g.k.FE=function(){this.Xq();return!!this.u&&this.u.C};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Xq();this.u&&(a?c?Z2(this.u,c,b):Z2(this.u,"YOUTUBE_DRAWER_AUTO_OPEN",b):$2(this.u))};
g.k.jz=function(a,b){this.player.V(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ca=function(){this.player.T().K.unsubscribe("vast_info_card_add",this.vG,this);g.sn(this.player.getRootNode(),g.YY.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.vp(a[b]);this.X.length=0;g.IS.prototype.ca.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.D(this,a);return a.element};g.pU.annotations_module=m3;g.pU.creatorendscreen=C2;})(_yt_player);
