(function(g){var window=this;var eHa=function(a,b){return g.Pb(a,b)},Z5=function(a,b,c){a.C.set(b,c)},$5=function(a){Z5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.A()).toString(36));
return a},a6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.bn(a.C,b,c)},fHa=function(a,b){var c=[];
g.hj(b,function(d){try{var e=g.Qn.prototype.B.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Pn(e)&&c.push(d)},a);
return c},gHa=function(a,b){var c=fHa(a,b);
g.Cb(c,function(d){g.Qn.prototype.remove.call(this,d)},a)},hHa=function(a){if(a.xe){if(a.xe.locationOverrideToken)return{locationOverrideToken:a.xe.locationOverrideToken};
if(null!=a.xe.latitudeE7&&null!=a.xe.longitudeE7)return{latitudeE7:a.xe.latitudeE7,longitudeE7:a.xe.longitudeE7}}return null},iHa=function(a,b){g.jb(a,b)||a.push(b)},b6=function(a){var b=0,c;
for(c in a)b++;return b},jHa=function(a,b){var c=b instanceof g.Ec?b:g.Kc(b,/^data:image\//i.test(b));
a.src=g.Fc(c)},c6=function(){},kHa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},lHa=function(a){if(a.If&&"function"==typeof a.If)return a.If();
if("string"===typeof a)return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Lb(a)},mHa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||"string"===typeof a)g.Cb(a,b,void 0);else{if(a.Tg&&"function"==typeof a.Tg)var c=a.Tg();else if(a.If&&"function"==typeof a.If)c=void 0;else if(g.Na(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Mb(a);d=lHa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},nHa=function(a,b,c,d){var e=new g.Qm(null,void 0);
a&&g.Rm(e,a);b&&g.Sm(e,b);c&&g.Tm(e,c);d&&(e.B=d);return e},d6=function(a,b){g.Lo[a]=!0;
var c=g.Jo();c&&c.publish.apply(c,arguments);g.Lo[a]=!1},e6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Nm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",oHa(this,a.capabilities||""),pHa(this,a.experiments||""))},oHa=function(a,b){a.capabilities.clear();
g.Ke(b.split(","),g.Ta(eHa,qHa)).forEach(function(c){a.capabilities.add(c)})},pHa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},f6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},g6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},rHa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},sHa=function(a){return new f6(a)},tHa=function(a){return Array.isArray(a)?g.Oc(a,sHa):[]},h6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},i6=function(a){return Array.isArray(a)?"["+g.Oc(a,h6).join(",")+"]":"null"},j6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},uHa=function(a){return g.Oc(a,function(b){return{key:b.id,
name:b.name}})},k6=function(a,b){return g.fb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},l6=function(a,b){return g.fb(a,function(c){return g6(c,b)})},vHa=function(){var a=(0,g.iu)();
a&&gHa(a,a.u.xj(!0))},m6=function(){var a=g.lu("yt-remote-connected-devices")||[];
g.zb(a);return a},wHa=function(a){if(g.kb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Oc(a,function(d,e){return 0==e?d:d.substring(c.length)})},xHa=function(a){g.ku("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.lu("yt-remote-device-id");a||(a=j6(),g.ku("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.jb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.jb(a,b);g.nu()&&g.Bb(a,b);a=wHa(a);if(g.kb(a))try{g.yq("remote_sid")}catch(c){}else try{g.wq("remote_sid",a.join(","),-1)}catch(c){}},yHa=function(){return g.lu("yt-remote-session-browser-channel")},zHa=function(){return g.lu("yt-remote-local-screens")||[]},AHa=function(){g.ku("yt-remote-lounge-token-expiration",!0,86400)},BHa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Oc(zHa(),function(d){return d.loungeToken}),c=g.Oc(a,function(d){return d.loungeToken});
g.qh(c,function(d){return!g.jb(b,d)})&&AHa();
g.ku("yt-remote-local-screens",a,31536E3)},CHa=function(a,b){g.ku("yt-remote-session-browser-channel",a);
g.ku("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.jb(c,d)||c.push(d);xHa(c);p6()},q6=function(a){a||(g.mu("yt-remote-session-screen-id"),g.mu("yt-remote-session-video-id"));
p6();a=m6();g.ob(a,o6());xHa(a)},DHa=function(){if(!r6){var a=g.jo();
a&&(r6=new g.Kn(a))}},EHa=function(){DHa();
return r6?!!r6.get("yt-remote-use-staging-server"):!1},FHa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},GHa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?HHa(a.shift(),function(){s6(a)}):t6()},IHa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},HHa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.kd(d,g.sg(a));(document.head||document.documentElement).appendChild(d)},t6=function(){var a=GHa();
a&&a(!1,"No cast extension found")},KHa=function(){if(JHa){var a=2,b=GHa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;HHa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},LHa=function(){KHa();
var a=(a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/))?parseInt(a[1],10):0;var b=[];if(0!=a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}b.push("//www.gstatic.com/eureka/clank/cast_sender.js");s6(b)},u6=function(a,b,c){g.C.call(this);
this.I=null!=c?(0,g.z)(a,c):a;this.zf=b;this.F=(0,g.z)(this.DK,this);this.u=!1;this.B=0;this.C=this.Za=null;this.D=[]},v6=function(a,b,c){g.C.call(this);
this.D=null!=c?a.bind(c):a;this.zf=b;this.C=null;this.u=!1;this.B=0;this.Za=null},w6=function(a){a.Za=g.Lm(function(){a.Za=null;
a.u&&!a.B&&(a.u=!1,w6(a))},a.zf);
var b=a.C;a.C=null;a.D.apply(null,b)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return kHa(a)},y6=function(){},z6=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},B6=function(a){A6.dispatchEvent(new MHa(A6,a))},MHa=function(a){g.El.call(this,"statevent",a)},C6=function(){},NHa=function(){},PHa=function(a){return(a=OHa(a))?new ActiveXObject(a):new XMLHttpRequest},OHa=function(a){if(!a.B&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.B=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.B},D6=function(a,b,c,d){this.u=a;
this.B=b;this.R=c;this.K=d||1;this.F=45E3;this.D=new g.f1(this);this.C=new g.Km;this.C.setInterval(250)},RHa=function(a,b,c){a.qp=1;
a.Ck=$5(b.clone());a.bn=c;a.I=!0;QHa(a,null)},E6=function(a,b,c,d,e){a.qp=1;
a.Ck=$5(b.clone());a.bn=null;a.I=c;e&&(a.wH=!1);QHa(a,d)},QHa=function(a,b){a.hp=g.A();
F6(a);a.Gl=a.Ck.clone();a6(a.Gl,"t",a.K);a.Cs=0;a.ye=a.u.Dx(a.u.Yr()?b:null);0<a.ty&&(a.Rv=new v6((0,g.z)(a.BI,a,a.ye),a.ty));a.D.wa(a.ye,"readystatechange",a.ER);var c=a.Dm?g.Vb(a.Dm):{};a.bn?(a.Bw="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.ye.send(a.Gl,a.Bw,a.bn,c)):(a.Bw="GET",a.wH&&!g.Ae&&(c.Connection="close"),a.ye.send(a.Gl,a.Bw,null,c));a.u.Yh(1)},UHa=function(a,b,c){for(var d=!0;!a.hm&&a.Cs<c.length;){var e=SHa(a,c);
if(e==G6){4==b&&(a.Vk=4,B6(15),d=!1);break}else if(e==THa){a.Vk=4;B6(16);d=!1;break}else H6(a,e)}4==b&&0==c.length&&(a.Vk=1,B6(17),d=!1);a.ki=a.ki&&d;d||(I6(a),J6(a))},SHa=function(a,b){var c=a.Cs,d=b.indexOf("\n",c);
if(-1==d)return G6;c=Number(b.substring(c,d));if(isNaN(c))return THa;d+=1;if(d+c>b.length)return G6;var e=b.substr(d,c);a.Cs=d+c;return e},WHa=function(a,b){a.hp=g.A();
F6(a);var c=b?window.location.hostname:"";a.Gl=a.Ck.clone();Z5(a.Gl,"DOMAIN",c);Z5(a.Gl,"t",a.K);try{a.ri=new ActiveXObject("htmlfile")}catch(n){I6(a);a.Vk=7;B6(22);J6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in K6)h=K6[h];else if(h in VHa)h=K6[h]=VHa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
K6[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.fd(g.gc("b/12014412"),d+"</body></html>");a.ri.open();a.ri.write(g.bd(c));a.ri.close();a.ri.parentWindow.m=(0,g.z)(a.WQ,a);a.ri.parentWindow.d=(0,g.z)(a.uG,a,!0);a.ri.parentWindow.rpcClose=(0,g.z)(a.uG,a,!1);c=a.ri.createElement("DIV");a.ri.parentWindow.document.body.appendChild(c);d=g.Jc(a.Gl.toString());d=g.od(g.Fc(d));d=g.fd(g.gc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.gd(c,d);a.u.Yh(1)},F6=function(a){a.fB=g.A()+a.F;
XHa(a,a.F)},XHa=function(a,b){if(null!=a.Bp)throw Error("WatchDog timer not null");
a.Bp=z6((0,g.z)(a.fR,a),b)},L6=function(a){a.Bp&&(g.v.clearTimeout(a.Bp),a.Bp=null)},J6=function(a){a.u.wD()||a.hm||a.u.cu(a)},I6=function(a){L6(a);
g.fg(a.Rv);a.Rv=null;a.C.stop();g.oBa(a.D);if(a.ye){var b=a.ye;a.ye=null;b.abort();b.dispose()}a.ri&&(a.ri=null)},H6=function(a,b){try{a.u.mG(a,b),a.u.Yh(4)}catch(c){}},ZHa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;YHa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){ZHa(a,b,c,d,f)},f)})}},YHa=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
jHa(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},N6=function(a){g.am.call(this);
this.headers=new g.Nm;this.fa=a||null;this.C=!1;this.ba=this.u=null;this.Aa=this.P="";this.I=0;this.D="";this.F=this.ma=this.R=this.ha=!1;this.K=0;this.X=null;this.Ja="";this.Y=this.ka=!1},$Ha=function(a){return g.ye&&g.ae(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},aIa=function(a){return"content-type"==a.toLowerCase()},cIa=function(a,b){a.C=!1;
a.u&&(a.F=!0,a.u.abort(),a.F=!1);a.D=b;a.I=5;bIa(a);O6(a)},bIa=function(a){a.ha||(a.ha=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},eIa=function(a){if(a.C&&"undefined"!=typeof g.k1)if(a.ba[1]&&4==P6(a)&&2==a.getStatus())Q6(a,"Local request error detected and ignored");
else if(a.R&&4==P6(a))g.Lm(a.jG,0,a);else if(a.dispatchEvent("readystatechange"),4==P6(a)){Q6(a,"Request complete");a.C=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.xd(1,String(a.P));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!dIa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<P6(a)?a.u.statusText:""}catch(m){l=""}a.D=l+" ["+a.getStatus()+"]";bIa(a)}}finally{O6(a)}}},O6=function(a,b){if(a.u){fIa(a);
var c=a.u,d=a.ba[0]?g.Ka:null;a.u=null;a.ba=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},fIa=function(a){a.u&&a.Y&&(a.u.ontimeout=null);
a.X&&(g.v.clearTimeout(a.X),a.X=null)},P6=function(a){return a.u?a.u.readyState:0},R6=function(a){try{return a.u?a.u.responseText:""}catch(b){return""}},Q6=function(a,b){return b+" ["+a.Aa+" "+a.P+" "+a.getStatus()+"]"},gIa=function(a){this.u=a;
this.B=new y6},hIa=function(a){var b=S6(a.u,a.Tp,"/mail/images/cleardot.gif");
$5(b);ZHa(b.toString(),5E3,(0,g.z)(a.DJ,a),3,2E3);a.Yh(1)},U6=function(a){var b=a.u.R;
if(null!=b)B6(5),b?(B6(11),T6(a.u,a,!1)):(B6(12),T6(a.u,a,!0));else if(a.jg=new D6(a,void 0,void 0,void 0),a.jg.Dm=a.ry,b=a.u,b=S6(b,b.Yr()?a.Eq:null,a.sy),B6(5),!g.ye||g.be(10))a6(b,"TYPE","xmlhttp"),E6(a.jg,b,!1,a.Eq,!1);else{a6(b,"TYPE","html");var c=a.jg;a=!!a.Eq;c.qp=3;c.Ck=$5(b.clone());WHa(c,a)}},V6=function(a,b,c){this.Ka=1;
this.u=[];this.C=[];this.D=new y6;this.K=a||null;this.R=null!=b?b:null;this.F=c||!1},iIa=function(a,b){this.u=a;
this.map=b;this.context=null},lIa=function(a,b,c,d){g.El.call(this,"timingevent",a);
this.size=b;this.Pr=d},mIa=function(a){g.El.call(this,"serverreachability",a)},pIa=function(a){nIa(a);
if(3==a.Ka){var b=a.rr++,c=a.Ht.clone();Z5(c,"SID",a.B);Z5(c,"RID",b);Z5(c,"TYPE","terminate");W6(a,c);b=new D6(a,a.B,b,void 0);b.qp=2;b.Ck=$5(c.clone());jHa(new Image,b.Ck.toString());b.hp=g.A();F6(b)}oIa(a)},qIa=function(a){a.cK(1,0);
a.Ht=S6(a,null,a.qy);X6(a)},nIa=function(a){a.Hk&&(a.Hk.abort(),a.Hk=null);
a.Td&&(a.Td.cancel(),a.Td=null);a.zj&&(g.v.clearTimeout(a.zj),a.zj=null);Y6(a);a.Xf&&(a.Xf.cancel(),a.Xf=null);a.Lk&&(g.v.clearTimeout(a.Lk),a.Lk=null)},rIa=function(a,b){if(0==a.Ka)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new iIa(a.NN++,b));2!=a.Ka&&3!=a.Ka||X6(a)},sIa=function(a){var b=0;
a.Td&&b++;a.Xf&&b++;return b},X6=function(a){a.Xf||a.Lk||(a.Lk=z6((0,g.z)(a.tG,a),0),a.bo=0)},uIa=function(a,b){if(1==a.Ka){if(!b){a.rr=Math.floor(1E5*Math.random());
var c=a.rr++,d=new D6(a,"",c,void 0);d.Dm=a.Uk;var e=Z6(a),f=a.Ht.clone();Z5(f,"RID",c);Z5(f,"CVER","1");W6(a,f);RHa(d,f,e);a.Xf=d;a.Ka=2}}else 3==a.Ka&&(b?tIa(a,b):0==a.u.length||a.Xf||tIa(a))},tIa=function(a,b){if(b)if(6<a.im){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.rr-1;var d=Z6(a)}else c=b.R,d=b.bn;else c=a.rr++,d=Z6(a);var e=a.Ht.clone();Z5(e,"SID",a.B);Z5(e,"RID",c);Z5(e,"AID",a.vo);W6(a,e);c=new D6(a,a.B,c,a.bo+1);c.Dm=a.Uk;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Xf=c;RHa(c,e,d)},W6=function(a,b){if(a.wf){var c=a.wf.ZC();
c&&g.Eb(c,function(d,e){Z5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.im&&0<b){var d=a.u[0].u;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={zn:e.zn},f++){e.zn=a.u[f].u;var h=a.u[f].map;e.zn=6>=a.im?f:e.zn-d;try{g.Eb(h,function(l){return function(m,n){c.push("req"+l.zn+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.zn+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},vIa=function(a){a.Td||a.zj||(a.I=1,a.zj=z6((0,g.z)(a.sG,a),0),a.On=0)},$6=function(a){if(a.Td||a.zj||3<=a.On)return!1;
a.I++;a.zj=z6((0,g.z)(a.sG,a),wIa(a,a.On));a.On++;return!0},T6=function(a,b,c){a.yw=c;
a.Si=b.Mj;a.F||qIa(a)},Y6=function(a){null!=a.nm&&(g.v.clearTimeout(a.nm),a.nm=null)},wIa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.wf&&(c=null);var d=(0,g.z)(a.nS,a);c||(c=new g.Qm("//www.google.com/images/cleardot.gif"),$5(c));YHa(c.toString(),1E4,d)}else B6(2);xIa(a,b)},xIa=function(a,b){a.Ka=0;
a.wf&&a.wf.nC(b);oIa(a);nIa(a)},oIa=function(a){a.Ka=0;
a.Si=-1;if(a.wf)if(0==a.C.length&&0==a.u.length)a.wf.sx();else{g.rb(a.C);var b=g.rb(a.u);a.C.length=0;a.u.length=0;a.wf.sx(b)}},S6=function(a,b,c){var d=g.Ym(c);
if(""!=d.u)b&&g.Sm(d,b+"."+d.u),g.Tm(d,d.D);else{var e=window.location;d=nHa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.lq&&g.Eb(a.lq,function(f,h){Z5(d,h,f)});
Z5(d,"VER",a.im);W6(a,d);return d},yIa=function(){},zIa=function(){this.u=[];
this.B=[]},AIa=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.C.call(this);
this.u=new g.F(this.PQ,0,this);g.D(this,this.u);this.zf=5E3;this.B=0;if("function"===typeof a)b&&(a=(0,g.z)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},c7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.ba=a;this.I=b;this.C=new g.Jn;this.B=new b7(this.QR,this);this.u=null;this.X=!1;this.F=null;this.P="";this.R=this.D=0;this.K=[];this.fa=c;this.Y=d},BIa=function(a){return{firstTestResults:[""],
secondTestResults:!a.u.yw,sessionId:a.u.B,arrayId:a.u.vo}},CIa=function(a,b){a.R=b||0;
a.B.stop();d7(a);a.u&&(3==a.u.getState()&&uIa(a.u),pIa(a.u));a.R=0},e7=function(a){return!!a.u&&3==a.u.getState()},d7=function(a){if(a.u){var b=a.Y(),c=a.u.Uk||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.u.Uk=c}},DIa=function(a,b){(a.I.loungeIdToken=b)||a.B.stop()},f7=function(a){this.scheme="https";
this.port=this.domain="";this.u="/api/lounge";this.B=!0;a=a||document.location.href;var b=Number(g.xd(4,a))||"";b&&(this.port=":"+b);this.domain=g.yd(a)||"";a=g.Vc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Cc(a,"10.0")&&(this.B=!1))},g7=function(a,b){var c=a.u;
a.B&&(c=a.scheme+"://"+a.domain+a.port+a.u);return g.Md(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ta(a.D,d,!0),onError:g.Ta(a.C,e),Cg:g.Ta(a.F,e)};c&&(a.uc=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.qq(b,a)},HIa=function(){var a=EIa;
FIa();i7.push(a);GIa(i7)},j7=function(a,b){FIa();
var c=i7,d=IIa(a,String(b));g.kb(c)?JIa(d):(GIa(c),g.Cb(c,function(e){e(d)}))},FIa=function(){i7||(i7=g.Ja("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",i7,void 0))},JIa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},GIa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];g.Cb(a,function(f){f(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},IIa=function(a,b){var c=(g.A()-KIa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.O.call(this);
this.I=a;this.screens=[]},LIa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},MIa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ke(a.screens,function(f){return!!k6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=LIa(a,b[d])||c;return c},NIa=function(a,b){var c=a.screens.length;
a.screens=g.Ke(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},o7=function(a,b,c,d){g.O.call(this);
this.I=a;this.F=b;this.C=c;this.D=d;this.B=0;this.u=null;this.Za=NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.B=a;this.u=NaN;p7(this);this.info("Initializing with "+i6(this.screens))},OIa=function(a){if(a.screens.length){var b=g.Oc(a.screens,function(d){return d.id}),c=g7(a.B,"/pairing/get_lounge_token_batch");
h7(a.B,c,{screen_ids:b.join(",")},(0,g.z)(a.LK,a),(0,g.z)(a.KK,a))}},p7=function(a){if(g.vo("deprecate_pair_servlet_enabled"))return MIa(a,[]);
var b=tHa(zHa());b=g.Ke(b,function(c){return!c.uuid});
return MIa(a,b)},r7=function(a,b){BHa(g.Oc(a.screens,rHa));
b&&AHa()},t7=function(a,b){g.O.call(this);
this.I=b;var c=g.lu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.jb(c,l)}this.u=d;this.F=a;this.C=this.D=NaN;this.B=null;s7("Initialized with "+g.Kj(this.u))},PIa=function(a,b,c){var d=g7(a.F,"/pairing/get_screen_availability");
h7(a.F,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},u7=function(a,b){a:if(b6(b)!=b6(a.u))var c=!1;
else{c=g.Mb(b);for(var d=0,e=c.length;d<e;++d)if(!a.u[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Kj(a.u)),a.u=b,a.V("screenChange"));QIa(a)},v7=function(a){isNaN(a.C)||g.Io(a.C);
a.C=g.Go((0,g.z)(a.hA,a),0<a.D&&a.D<g.A()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},RIa=function(a){var b={};
g.Cb(a.I(),function(c){c.token?b[c.token]=c.id:this.Dd("Requesting availability of screen w/o lounge token.")});
return b},QIa=function(a){a=g.Mb(g.Fb(a.u,function(b){return b}));
g.zb(a);a.length?g.ku("yt-remote-online-screen-ids",a.join(","),60):g.mu("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.F=a;this.u=this.B=null;this.C=[];this.D={};SIa(this)},UIa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.tg();if(h=(c?l6(h,c):null)||l6(h,b)){h.uuid=b;var l=x7(a,h);PIa(a.u,l,function(m){e(m?l:null)})}else c?TIa(a,c,(0,g.z)(function(m){var n=x7(this,new f6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));PIa(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},VIa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},TIa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={uc:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.qq(g7(a.F,"/pairing/get_lounge_token_batch"),e)},WIa=function(a){a.screens=a.B.tg();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+i6(a.screens))},SIa=function(a){y7(a);
a.B=new q7(a.F);a.B.subscribe("screenChange",(0,g.z)(a.RK,a));WIa(a);a.C=tHa(g.lu("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+i6(a.C));a.u=new t7(a.F,(0,g.z)(a.tg,a,!0));a.u.subscribe("screenChange",(0,g.z)(function(){this.V("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=l6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.ku("yt-remote-automatic-screen-cache",g.Oc(a.C,rHa)));y7(a);a.D[b.uuid]=b.id;g.ku("yt-remote-device-id-map",a.D,31536E3);return b},y7=function(a){a.D=g.lu("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.O.call(this);
this.ba=c;this.R=a;this.u=b;this.K=null},A7=function(a,b){j7(a.ba,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.B=null;this.C=0;this.F=(0,g.z)(this.RS,this);this.D=(0,g.z)(this.mR,this);this.C=g.Go((0,g.z)(function(){XIa(this,null)},this),12E4)},YIa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kj(void 0));
var b={type:"getMdxSessionStatus"};a.B?a.B.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ka,(0,g.z)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Kj(b))},XIa=function(a,b){g.Io(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.z)(a.Bv,a),d=(0,g.z)(a.Ag,a);a.pD(b,c,d,5)}}else a.Ag(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.C=this.I=null;this.P="";this.fa=c;this.X=null;this.F=g.Ka;this.D=NaN;this.Y=(0,g.z)(this.VS,this);this.B=g.Ka},ZIa=function(a){a.B=a.R.JI(a.P,a.u.label,a.u.friendlyName,(0,g.z)(function(b){this.B=g.Ka;
this.Bv(b)},a),(0,g.z)(function(b){this.B=g.Ka;
this.Ag(b)},a))},$Ia=function(a){var b={};
b.pairingCode=a.P;b.theme=a.fa;EHa()&&(b.env_useStageMdx=1);return g.Hd(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.B=g.Go((0,g.z)(this.wo,this,null),150)},E7=function(a,b){g.O.call(this);
this.B=a;this.K=b.appId||"233637DE";this.I=b.theme||"cl";this.R=b.disableCastApi||!1;this.u=null;this.F=!1;this.C=[];this.D=(0,g.z)(this.eQ,this)},aJa=function(a,b){return b?g.fb(a.C,function(c){return g6(b,c.label)},a):null},F7=function(a){j7("Controller",a)},EIa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G7=function(a){return a.F||!!a.C.length||!!a.u},H7=function(a,b,c){b!=a.u&&(g.fg(a.u),(a.u=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.u):a.V("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.z)(a.qG,a,b)),b.getScreen()?a.V("yt-remote-cast2-session-change",b.getScreen()):c&&a.u.wo(null)):a.V("yt-remote-cast2-session-change",null))},bJa=function(a){var b=a.B.II(),c=a.u&&a.u.u;
a=g.Oc(b,function(d){c&&g6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=aJa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},hJa=function(a,b,c,d){d.disableCastApi?I7("Cannot initialize because disabled by Mdx config."):cJa()?dJa(b,d)&&(J7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?eJa(a,c):(window.__onGCastApiAvailable=function(e,f){e?eJa(a,c):(K7("Failed to load cast API: "+f),L7(!1),J7(!1),g.mu("yt-remote-cast-available"),g.mu("yt-remote-cast-receiver"),
fJa(),c(!1))},d.loadCastApiSetupScript?g.So("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?LHa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(KHa(),s6(gJa.map(IHa))))):I7("Cannot initialize because not running Chrome")},fJa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);iJa(!1);g.Oo(N7);N7.length=0},O7=function(){return!!g.lu("yt-remote-cast-installed")},jJa=function(){var a=g.lu("yt-remote-cast-receiver");
return a?a.friendlyName:null},kJa=function(){I7("clearCurrentReceiver");
g.mu("yt-remote-cast-receiver")},lJa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.No("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},cJa=function(){var a=0<=g.Vc.search(/ (CrMo|Chrome|CriOS)\//);
return g.pB||a},mJa=function(a,b){M7().init(a,b)},dJa=function(a,b){var c=!1;
M7()||(c=new E7(a,b),c.subscribe("yt-remote-cast2-availability-change",function(d){g.ku("yt-remote-cast-available",d);d6("yt-remote-cast2-availability-change",d)}),c.subscribe("yt-remote-cast2-receiver-selected",function(d){I7("onReceiverSelected: "+d.friendlyName);
g.ku("yt-remote-cast-receiver",d);d6("yt-remote-cast2-receiver-selected",d)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(d){I7("onReceiverResumed: "+d.friendlyName);
g.ku("yt-remote-cast-receiver",d)}),c.subscribe("yt-remote-cast2-session-change",function(d){I7("onSessionChange: "+h6(d));
d||g.mu("yt-remote-cast-receiver");d6("yt-remote-cast2-session-change",d)}),g.Fa("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
I7("cloudview.createSingleton_: "+c);return c},M7=function(){return g.Ja("yt.mdx.remote.cloudview.instance_")},eJa=function(a,b){L7(!0);
J7(!1);mJa(a,function(c){c?(iJa(!0),g.Po("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.mu("yt-remote-cast-available"),g.mu("yt-remote-cast-receiver"),fJa());b(c)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.ku("yt-remote-cast-installed",a)},P7=function(){return!!g.Ja("yt.mdx.remote.cloudview.apiReady_")},iJa=function(a){I7("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.K=this.R=0;this.u=null;this.hasNext=this.Ui=!1;this.P=this.I=this.B=this.F=0;this.D=NaN;this.C=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.u=null;a.playerState=-1;a.Ui=!1;a.hasNext=!1;a.R=0;a.K=g.A();a.F=0;a.B=0;a.I=0;a.P=0;a.D=NaN;a.C=!1},U7=function(a){return a.Hb()?(g.A()-a.K)/1E3:0},V7=function(a,b){a.R=b;
a.K=g.A()},W7=function(a){switch(a.playerState){case 1:case 1081:return(g.A()-a.K)/1E3+a.R;
case -1E3:return 0}return a.R},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Wb(a.u);b.hasPrevious=a.Ui;b.hasNext=a.hasNext;b.playerTime=a.R;b.playerTimeAt=a.K;b.seekableStart=a.F;b.seekableEnd=a.B;b.duration=a.I;b.loadedTime=a.P;b.liveIngestionTime=a.D;return b},$7=function(a,b){g.O.call(this);
this.Ka=0;this.C=a;this.F=[];this.D=new zIa;this.B=this.u=null;this.R=(0,g.z)(this.zO,this);this.I=(0,g.z)(this.tr,this);this.K=(0,g.z)(this.yO,this);this.P=(0,g.z)(this.GO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.wA,this),nJa(this))):c=3;0!=c&&(b?this.wA(c):g.Go((0,g.z)(function(){this.wA(c)},this),0));
var d=lJa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.P)},a8=function(a){return new S7(a.C.getPlayerContextData())},nJa=function(a){g.Cb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.C.subscribe(b,g.Ta(this.aQ,b),this))},a)},oJa=function(a){g.Cb(a.F,function(b){this.C.unsubscribeByKey(b)},a);
a.F.length=0},b8=function(a){return 1==a.getState()},c8=function(a,b){var c=a.D;
50>c.u.length+c.B.length&&a.D.B.push(b)},e8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.C.sendMessage(b,c)},d8=function(a,b){oJa(a);
a.C.setPlayerContextData(Y7(b));nJa(a)},Z7=function(a,b){a.B&&(a.B.removeUpdateListener(a.R),a.B.removeMediaListener(a.I),a.tr(null));
a.B=b;a.B&&(j7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.R),a.B.addMediaListener(a.I),a.B.media.length&&a.tr(a.B.media[0]))},pJa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V7(d,a.u.getEstimatedTime());d8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.z)(function(d){this.Dd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Dd("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.O.call(this);
this.F=NaN;this.Y=!1;this.R=this.K=this.P=this.X=NaN;this.ba=[];this.D=this.I=this.C=this.Lb=this.u=null;this.ha=a;this.ba.push(g.cp(window,"beforeunload",(0,g.z)(this.FK,this)));this.B=[];this.Lb=new S7;this.fa=b.id;this.u=qJa(this,c);this.u.subscribe("handlerOpened",this.DO,this);this.u.subscribe("handlerClosed",this.AO,this);this.u.subscribe("handlerError",this.BO,this);this.u.subscribe("handlerMessage",this.CO,this);DIa(this.u,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Lb.videoId;
g.nu()&&g.ku("yt-remote-session-video-id",d)},this)},i8=function(a){j7("conn",a)},qJa=function(a,b){return new c7(g7(a.ha,"/bc"),b,!1,function(){return a.FI()})},j8=function(a,b){a.V("proxyStateChange",b)},rJa=function(a){a.F=g.Go((0,g.z)(function(){i8("Connecting timeout");
this.Wn(1)},a),2E4)},k8=function(a){g.Io(a.F);
a.F=NaN},l8=function(a){g.Io(a.X);
a.X=NaN},sJa=function(a){m8(a);
a.P=g.Go((0,g.z)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.Io(a.P);
a.P=NaN},uJa=function(a,b){b&&(k8(a),l8(a));
var c=e7(a.u)&&isNaN(a.F);b==c?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.oD()&&a.Lb.reset(),j8(a,1),n8(a,"getNowPlaying"),tJa(a)):a.Wn(1)},vJa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Lb.videoId&&(g.Sb(b.params)?a.Lb.u=null:a.Lb.u=b.params,a.V("remotePlayerChange"))},wJa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Lb.listId=b.params.listId||a.Lb.listId;X7(a.Lb,c,d);a.V("remoteQueueChange")},yJa=function(a,b){b.params=b.params||{};
wJa(a,b);xJa(a,b);a.V("autoplayDismissed")},xJa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V7(a.Lb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Lb.playerState&&(c=-1E3);a.Lb.playerState=c;c=Number(b.params.loadedTime);a.Lb.P=isNaN(c)?0:c;a.Lb.hi(Number(b.params.duration));c=a.Lb;var d=Number(b.params.liveIngestionTime);c.D=d;c.C=isNaN(d)?!1:!0;c=a.Lb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.F=isNaN(d)?0:d;c.B=isNaN(e)?0:e;1==a.Lb.playerState?sJa(a):m8(a);a.V("remotePlayerChange")},zJa=function(a,b){if(-1E3!=a.Lb.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Lb.playerState=c;c=parseInt(b.params.currentTime,10);V7(a.Lb,isNaN(c)?0:c);a.V("remotePlayerChange")}},AJa=function(a,b){var c="true"==b.params.muted;
a.Lb.volume=parseInt(b.params.volume,10);a.Lb.muted=c;a.V("remotePlayerChange")},BJa=function(a,b){a.I=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},CJa=function(a,b){var c="true"==b.params.hasNext;
a.Lb.Ui="true"==b.params.hasPrevious;a.Lb.hasNext=c;a.V("previousNextChange")},tJa=function(a){g.Io(a.R);
a.R=g.Go((0,g.z)(a.Wn,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.Kj(c)):i8("Sending: action="+b);
a.u.sendMessage(b,c)},o8=function(a){n7.call(this,"ScreenServiceProxy");
this.yf=a;this.u=[];this.u.push(this.yf.$_s("screenChange",(0,g.z)(this.EL,this)));this.u.push(this.yf.$_s("onlineScreenChange",(0,g.z)(this.HP,this)))},GJa=function(a,b){DHa();
if(!r6||!r6.get("yt-remote-disable-remote-module-for-dev")){b=g.L("MDX_CONFIG")||b;vHa();p6();p8||(p8=new f7(b?b.loungeApiHost:void 0),EHa()&&(p8.u="/api/loungedev"));q8||(q8=g.Ja("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",q8,void 0));DJa();var c=r8();if(!c){var d=new w7(p8);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=r8();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,disableCastApi:b.disableCastApi,
enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});hJa(a,d,function(h){h?s8()&&R7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){d6("yt-remote-receiver-availability-change")})},e)}if(b&&!g.Ja("yt.mdx.remote.initialized_")){g.Fa("yt.mdx.remote.initialized_",!0,void 0);
t8("Initializing: "+g.Kj(b));u8.push(g.No("yt-remote-cast2-availability-change",function(){d6("yt-remote-receiver-availability-change")}));
u8.push(g.No("yt-remote-cast2-receiver-selected",function(){v8(null);d6("yt-remote-auto-connect","cast-selector-receiver")}));
u8.push(g.No("yt-remote-cast2-receiver-resumed",function(){d6("yt-remote-receiver-resumed","cast-selector-receiver")}));
u8.push(g.No("yt-remote-cast2-session-change",EJa));u8.push(g.No("yt-remote-connection-change",function(h){h?R7(s8(),"YouTube TV"):w8()||(R7(null,null),kJa())}));
e=x8();b.isAuto&&(e.id+="#dial");g.vo("desktop_enable_autoplay")&&(e.capabilities=["atp"]);e.name=b.device;e.app=b.app;var f=b.theme;f&&(e.theme=f);t8(" -- with channel params: "+g.Kj(e));e?(g.ku("yt-remote-session-app",e.app),g.ku("yt-remote-session-name",e.name)):(g.mu("yt-remote-session-app"),g.mu("yt-remote-session-name"));g.Fa("yt.mdx.remote.channelParams_",e,void 0);c.start();s8()||FJa()}}},HJa=function(){var a=r8().yf.$_gos();
var b=y8();b&&z8()&&(k6(a,b)||a.push(b));return uHa(a)},A8=function(){var a=IJa();
!a&&O7()&&jJa()&&(a={key:"cast-selector-receiver",name:jJa()});return a},IJa=function(){var a=HJa(),b=y8();
b||(b=w8());return g.fb(a,function(c){return b&&g6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().tg();return l6(b,a)},EJa=function(a){t8("remote.onCastSessionChange_: "+h6(a));
if(a){var b=y8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){j7("remote",a)},r8=function(){if(!F8){var a=g.Ja("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.Ja("yt.mdx.remote.currentScreenId_")},JJa=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},KJa=function(){return g.Ja("yt.mdx.remote.connectData_")},v8=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.Ja("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||JJa("");g.Fa("yt.mdx.remote.connection_",a,void 0);q8&&(g.Cb(q8,function(c){c(a)}),q8.length=0);
b&&!a?d6("yt-remote-connection-change",!1):!b&&a&&d6("yt-remote-connection-change",!0)},w8=function(){var a=g.nu();
if(!a)return null;var b=r8();if(!b)return null;b=b.tg();return l6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{JJa(a.id);var c=new h8(p8,a,x8());c.connect(b,KJa());c.subscribe("beforeDisconnect",function(d){d6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},FJa=function(){var a=w8();
a?(t8("Resume connection to: "+h6(a)),C8(a,0)):(q6(),kJa(),t8("Skipping connecting because no session screen found."))},DJa=function(){var a=x8();
if(g.Sb(a)){a=o6();var b=g.lu("yt-remote-session-name")||"",c=g.lu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.Ja("yt.mdx.remote.channelParams_")||{}},I8=function(a,b,c){g.C.call(this);
var d=this;this.B=a;this.J=b;this.yb=c;this.events=new g.sR(this);this.X=this.events.N(this.J,"onVolumeChange",function(e){LJa(d,e)});
this.F=!1;this.suggestion=null;this.I=new g.AM(64);this.u=new g.F(this.IH,500,this);this.C=new g.F(this.JH,1E3,this);this.R=new u6(this.BS,0,this);this.D={};this.P=new g.F(this.pI,1E3,this);this.K=new v6(this.seekTo,1E3,this);this.Y=g.Ka;g.D(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.lP);this.events.N(b,"captionschanged",this.wO);this.events.N(b,"captionssettingschanged",this.OH);this.events.N(b,"videoplayerreset",this.Cv);this.events.N(b,"mdxautoplaycancel",function(){d.yb.KC()});
a=this.yb;a.na();a.subscribe("proxyStateChange",this.lG,this);a.subscribe("remotePlayerChange",this.yr,this);a.subscribe("remoteQueueChange",this.Cv,this);a.subscribe("previousNextChange",this.iG,this);a.subscribe("nowAutoplaying",this.dG,this);a.subscribe("autoplayDismissed",this.EF,this);g.D(this,this.u);g.D(this,this.C);g.D(this,this.R);g.D(this,this.P);g.D(this,this.K);this.OH();this.Cv();this.yr()},LJa=function(a,b){if(J8(a)){a.yb.unsubscribe("remotePlayerChange",a.yr,a);
var c=Math.round(b.volume),d=!!b.muted,e=a8(a.yb);if(c!==e.volume||d!==e.muted)a.yb.setVolume(c,d),a.P.start();a.yb.subscribe("remotePlayerChange",a.yr,a)}},MJa=function(a){a.tc(0);
a.u.stop();a.vb(new g.AM(64))},K8=function(a,b){if(J8(a)&&!a.F){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.Zb(c,b));a.yb.GI(a.J.getVideoData(1).videoId,c);a.D=a8(a.yb).u}},L8=function(a,b){var c=a.J.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.yb.playVideo(c.videoId,b,d,e,c.playerParams,c.Vg,hHa(c));a.vb(new g.AM(1))},NJa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{PD:1});
c&&c.length?(a.J.setOption("captions","track",b),a.F=!1):(a.J.loadModule("captions"),a.F=!0)}else a.J.setOption("captions","track",{})},J8=function(a){return a8(a.yb).videoId===a.J.getVideoData(1).videoId},M8=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{G:"div",L:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{G:"div",L:"ytp-mdx-manual-pairing-popup-title",Z:"Connecting to your TV on web using a code will be going away soon"},{G:"div",L:"ytp-mdx-manual-pairing-popup-buttons",S:[{G:"button",la:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],Z:"Learn more"},{G:"button",la:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],Z:"OK"}]}]}]});this.u=new g.lO(this,250);this.learnMoreButton=
this.ia("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ia("ytp-mdx-manual-pairing-popup-ok");g.D(this,this.u);this.N(this.learnMoreButton,"click",this.B);this.N(this.okButton,"click",this.C)},N8=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",S:[{G:"div",L:"ytp-mdx-popup-title",Z:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",Z:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",S:[{G:"button",la:["ytp-button","ytp-mdx-privacy-popup-cancel"],Z:"Cancel"},{G:"button",la:["ytp-button","ytp-mdx-privacy-popup-confirm"],
Z:"Confirm"}]}]}]});this.u=new g.lO(this,250);this.cancelButton=this.ia("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ia("ytp-mdx-privacy-popup-confirm");g.D(this,this.u);this.N(this.cancelButton,"click",this.B);this.N(this.confirmButton,"click",this.C)},O8=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",S:[{G:"div",L:"ytp-remote-display-status",S:[{G:"div",L:"ytp-remote-display-status-icon",S:[g.Ona()]},{G:"div",L:"ytp-remote-display-status-text",Z:"{{statustext}}"}]}]});this.api=a;this.u=new g.lO(this,250);g.D(this,this.u);this.N(a,"presentingplayerstatechange",this.B);OJa(this,g.uK(a))},OJa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.tL("Error on $RECEIVER_NAME",c):b.Hb()||g.U(b,4)?g.tL("Playing on $RECEIVER_NAME",c):g.tL("Connected to $RECEIVER_NAME",c);a.ya("statustext",c);a.u.show()}else a.u.hide()},P8=function(a,b){g.vX.call(this,"Play on",0,a,b);
this.J=a;this.Fl={};this.N(a,"onMdxReceiversChange",this.D);this.N(a,"presentingplayerstatechange",this.D);this.D()},Q8=function(a){g.IS.call(this,a);
this.Rh={key:j6(),name:"This computer"};this.Ai=null;this.subscriptions=[];this.Sz=this.yb=null;this.Fl=[this.Rh];this.Ik=this.Rh;this.Qc=new g.AM(64);this.nE=0;this.Ke=-1;this.yo=null;this.Br=this.Ku=!1;this.an=this.Wo=null;if(!g.xD(this.player.T())){a=this.player;var b=g.AT(a);b&&(b=b.Rk())&&(b=new P8(a,b),g.D(this,b));b=new O8(a);g.D(this,b);g.AP(a,b.element,4);this.Wo=new N8;g.D(this,this.Wo);g.AP(a,this.Wo.element,4);g.Q(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.Q(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.yo=new M8,g.D(this,this.yo),g.AP(a,this.yo.element,4));this.Br=!!w8();this.Ku=!!g.lu("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.an&&(a.player.removeEventListener("presentingplayerstatechange",a.an),a.an=null)},PJa=function(a,b,c){a.Qc=c;
a.player.V("presentingplayerstatechange",new g.EK(c,b))},QJa=function(a,b,c){var d=!1;
1===b?d=!a.Br:2===b&&(d=!a.Ku);d&&g.GK(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.Ik.key)if(b.key===a.Rh.key)B8();
else{if(a.yo&&!a.Ku&&b!==a.Rh&&"cast-selector-receiver"!==b.key&&g.HD(a.player.T()))RJa(a);else{var c;(c=!g.Q(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.Br||!a.Wo);(c?0:g.HD(a.player.T())||g.LD(a.player.T()))&&SJa(a)}a.Ik=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.Q(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ma(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Vg,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=hHa(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.Kj(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,P7()?M7().setLaunchParams(c):K7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?d6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().tg(),(c=l6(c,b.key))&&C8(c,1))}},SJa=function(a){g.uK(a.player).Hb()?a.player.pauseVideo():(a.an=function(b){QJa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.an));
a.Wo&&a.Wo.Cc();z8()||(G8=!0)},RJa=function(a){g.uK(a.player).Hb()?a.player.pauseVideo():(a.an=function(b){QJa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.an));
a.yo&&a.yo.Cc();z8()||(G8=!0)},VHa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},K6={"'":"\\'"},TJa={},qHa={LT:"atp",R2:"ska",P1:"que",V_:"mus",Q2:"sus",rX:"dsp",j2:"seq",A_:"mic",qW:"dpa"},r6,n6="",JHa=FHa("loadCastFramework")||FHa("loadCastApplicationFramework"),gJa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Va(u6,g.C);g.k=u6.prototype;g.k.CK=function(a){this.D=arguments;this.u=!1;this.Za?this.C=g.A()+this.zf:this.Za=g.Lm(this.F,this.zf)};
g.k.stop=function(){this.Za&&(g.v.clearTimeout(this.Za),this.Za=null);this.C=null;this.u=!1;this.D=[]};
g.k.pause=function(){++this.B};
g.k.resume=function(){this.B&&(--this.B,!this.B&&this.u&&(this.u=!1,this.I.apply(null,this.D)))};
g.k.ca=function(){this.stop();u6.Kd.ca.call(this)};
g.k.DK=function(){this.C?(this.Za=g.Lm(this.F,this.C-g.A()),this.C=null):(this.Za=null,this.B?this.u=!0:(this.u=!1,this.I.apply(null,this.D)))};g.u(v6,g.C);g.k=v6.prototype;g.k.BE=function(a){this.C=arguments;this.Za||this.B?this.u=!0:w6(this)};
g.k.stop=function(){this.Za&&(g.v.clearTimeout(this.Za),this.Za=null,this.u=!1,this.C=null)};
g.k.pause=function(){this.B++};
g.k.resume=function(){this.B--;this.B||!this.u||this.Za||(this.u=!1,w6(this))};
g.k.ca=function(){g.C.prototype.ca.call(this);this.stop()};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};var A6=new g.am;g.u(MHa,g.El);C6.prototype.u=null;C6.prototype.getOptions=function(){var a;(a=this.u)||(a={},OHa(this)&&(a[0]=!0,a[1]=!0),a=this.u=a);return a};var T8;g.Va(NHa,C6);T8=new NHa;g.k=D6.prototype;g.k.Dm=null;g.k.ki=!1;g.k.Bp=null;g.k.fB=null;g.k.hp=null;g.k.qp=null;g.k.Ck=null;g.k.Gl=null;g.k.bn=null;g.k.ye=null;g.k.Cs=0;g.k.ri=null;g.k.Bw=null;g.k.Vk=null;g.k.Fq=-1;g.k.wH=!0;g.k.hm=!1;g.k.ty=0;g.k.Rv=null;var THa={},G6={};g.k=D6.prototype;g.k.setTimeout=function(a){this.F=a};
g.k.ER=function(a){a=a.target;var b=this.Rv;b&&3==P6(a)?b.BE():this.BI(a)};
g.k.BI=function(a){try{if(a==this.ye)a:{var b=P6(this.ye),c=this.ye.I,d=this.ye.getStatus();if(g.ye&&!g.be(10)||g.Ae&&!g.ae("420+")){if(4>b)break a}else if(3>b||3==b&&!g.xg&&!R6(this.ye))break a;this.hm||4!=b||7==c||(8==c||0>=d?this.u.Yh(3):this.u.Yh(2));L6(this);var e=this.ye.getStatus();this.Fq=e;var f=R6(this.ye);(this.ki=200==e)?(4==b&&I6(this),this.I?(UHa(this,b,f),g.xg&&this.ki&&3==b&&(this.D.wa(this.C,"tick",this.zR),this.C.start())):H6(this,f),this.ki&&!this.hm&&(4==b?this.u.cu(this):(this.ki=
!1,F6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Vk=3,B6(13)):(this.Vk=0,B6(14)),I6(this),J6(this))}}catch(h){this.ye&&R6(this.ye)}finally{}};
g.k.zR=function(){var a=P6(this.ye),b=R6(this.ye);this.Cs<b.length&&(L6(this),UHa(this,a,b),this.ki&&4!=a&&F6(this))};
g.k.WQ=function(a){z6((0,g.z)(this.VQ,this,a),0)};
g.k.VQ=function(a){this.hm||(L6(this),H6(this,a),F6(this))};
g.k.uG=function(a){z6((0,g.z)(this.UQ,this,a),0)};
g.k.UQ=function(a){this.hm||(I6(this),this.ki=a,this.u.cu(this),this.u.Yh(4))};
g.k.cancel=function(){this.hm=!0;I6(this)};
g.k.fR=function(){this.Bp=null;var a=g.A();0<=a-this.fB?(2!=this.qp&&this.u.Yh(3),I6(this),this.Vk=2,B6(18),J6(this)):XHa(this,this.fB-a)};
g.k.getLastError=function(){return this.Vk};g.Va(N6,g.am);var dIa=/^https?$/i,UJa=["POST","PUT"];g.k=N6.prototype;
g.k.send=function(a,b,c,d){if(this.u)throw Error("[goog.net.XhrIo] Object is active with another request="+this.P+"; newUri="+a);b=b?b.toUpperCase():"GET";this.P=a;this.D="";this.I=0;this.Aa=b;this.ha=!1;this.C=!0;this.u=this.fa?PHa(this.fa):PHa(T8);this.ba=this.fa?this.fa.getOptions():T8.getOptions();this.u.onreadystatechange=(0,g.z)(this.jG,this);try{c6(Q6(this,"Opening Xhr")),this.ma=!0,this.u.open(b,String(a),!0),this.ma=!1}catch(f){c6(Q6(this,"Error opening Xhr: "+f.message));cIa(this,f);return}a=
c||"";var e=this.headers.clone();d&&mHa(d,function(f,h){e.set(h,f)});
d=g.fb(e.Tg(),aIa);c=g.v.FormData&&a instanceof g.v.FormData;!g.jb(UJa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.u.setRequestHeader(h,f)},this);
this.Ja&&(this.u.responseType=this.Ja);"withCredentials"in this.u&&this.u.withCredentials!==this.ka&&(this.u.withCredentials=this.ka);try{fIa(this),0<this.K&&(this.Y=$Ha(this.u),c6(Q6(this,"Will abort after "+this.K+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.u.timeout=this.K,this.u.ontimeout=(0,g.z)(this.yD,this)):this.X=g.Lm(this.yD,this.K,this)),c6(Q6(this,"Sending request")),this.R=!0,this.u.send(a),this.R=!1}catch(f){c6(Q6(this,"Send error: "+f.message)),cIa(this,f)}};
g.k.yD=function(){"undefined"!=typeof g.k1&&this.u&&(this.D="Timed out after "+this.K+"ms, aborting",this.I=8,Q6(this,this.D),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.u&&this.C&&(Q6(this,"Aborting"),this.C=!1,this.F=!0,this.u.abort(),this.F=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),O6(this))};
g.k.ca=function(){this.u&&(this.C&&(this.C=!1,this.F=!0,this.u.abort(),this.F=!1),O6(this,!0));N6.Kd.ca.call(this)};
g.k.jG=function(){this.na()||(this.ma||this.R||this.F?eIa(this):this.dQ())};
g.k.dQ=function(){eIa(this)};
g.k.isActive=function(){return!!this.u};
g.k.getStatus=function(){try{return 2<P6(this)?this.u.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.D?this.D:String(this.D)};g.k=gIa.prototype;g.k.ry=null;g.k.jg=null;g.k.Sv=!1;g.k.xD=null;g.k.Ft=null;g.k.bz=null;g.k.sy=null;g.k.Ka=null;g.k.Mj=-1;g.k.Eq=null;g.k.Tp=null;g.k.connect=function(a){this.sy=a;a=S6(this.u,null,this.sy);B6(3);this.xD=g.A();var b=this.u.K;null!=b?(this.Eq=b[0],(this.Tp=b[1])?(this.Ka=1,hIa(this)):(this.Ka=2,U6(this))):(a6(a,"MODE","init"),this.jg=new D6(this,void 0,void 0,void 0),this.jg.Dm=this.ry,E6(this.jg,a,!1,null,!0),this.Ka=0)};
g.k.DJ=function(a){if(a)this.Ka=2,U6(this);else{B6(4);var b=this.u;b.Si=b.Hk.Mj;a7(b,9)}a&&this.Yh(2)};
g.k.Dx=function(a){return this.u.Dx(a)};
g.k.abort=function(){this.jg&&(this.jg.cancel(),this.jg=null);this.Mj=-1};
g.k.wD=function(){return!1};
g.k.mG=function(a,b){this.Mj=a.Fq;if(0==this.Ka)if(b){try{var c=this.B.parse(b)}catch(d){c=this.u;c.Si=this.Mj;a7(c,2);return}this.Eq=c[0];this.Tp=c[1]}else c=this.u,c.Si=this.Mj,a7(c,2);else if(2==this.Ka)if(this.Sv)B6(7),this.bz=g.A();else if("11111"==b){if(B6(6),this.Sv=!0,this.Ft=g.A(),c=this.Ft-this.xD,!g.ye||g.be(10)||500>c)this.Mj=200,this.jg.cancel(),B6(12),T6(this.u,this,!0)}else B6(8),this.Ft=this.bz=g.A(),this.Sv=!1};
g.k.cu=function(){this.Mj=this.jg.Fq;if(this.jg.ki)0==this.Ka?this.Tp?(this.Ka=1,hIa(this)):(this.Ka=2,U6(this)):2==this.Ka&&((!g.ye||g.be(10)?!this.Sv:200>this.bz-this.Ft)?(B6(11),T6(this.u,this,!1)):(B6(12),T6(this.u,this,!0)));else{0==this.Ka?B6(9):2==this.Ka&&B6(10);var a=this.u;this.jg.getLastError();a.Si=this.Mj;a7(a,2)}};
g.k.Yr=function(){return this.u.Yr()};
g.k.isActive=function(){return this.u.isActive()};
g.k.Yh=function(a){this.u.Yh(a)};g.k=V6.prototype;g.k.Uk=null;g.k.lq=null;g.k.Xf=null;g.k.Td=null;g.k.qy=null;g.k.Ht=null;g.k.aC=null;g.k.au=null;g.k.rr=0;g.k.NN=0;g.k.wf=null;g.k.Lk=null;g.k.zj=null;g.k.nm=null;g.k.Hk=null;g.k.yw=null;g.k.vo=-1;g.k.mE=-1;g.k.Si=-1;g.k.bo=0;g.k.On=0;g.k.im=8;g.Va(lIa,g.El);g.Va(mIa,g.El);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){B6(0);this.qy=b;this.lq=c||{};d&&void 0!==e&&(this.lq.OSID=d,this.lq.OAID=e);this.F?(z6((0,g.z)(this.tC,this,a),100),qIa(this)):this.tC(a)};
g.k.tC=function(a){this.Hk=new gIa(this);this.Hk.ry=this.Uk;this.Hk.B=this.D;this.Hk.connect(a)};
g.k.wD=function(){return 0==this.Ka};
g.k.getState=function(){return this.Ka};
g.k.tG=function(a){this.Lk=null;uIa(this,a)};
g.k.sG=function(){this.zj=null;this.Td=new D6(this,this.B,"rpc",this.I);this.Td.Dm=this.Uk;this.Td.ty=0;var a=this.aC.clone();Z5(a,"RID","rpc");Z5(a,"SID",this.B);Z5(a,"CI",this.yw?"0":"1");Z5(a,"AID",this.vo);W6(this,a);if(!g.ye||g.be(10))Z5(a,"TYPE","xmlhttp"),E6(this.Td,a,!0,this.au,!1);else{Z5(a,"TYPE","html");var b=this.Td,c=!!this.au;b.qp=3;b.Ck=$5(a.clone());WHa(b,c)}};
g.k.mG=function(a,b){if(0!=this.Ka&&(this.Td==a||this.Xf==a))if(this.Si=a.Fq,this.Xf==a&&3==this.Ka)if(7<this.im){try{var c=this.D.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.zj){if(this.Td)if(this.Td.hp+3E3<this.Xf.hp)Y6(this),this.Td.cancel(),this.Td=null;else break a;$6(this);B6(19)}}else this.mE=c[1],0<this.mE-this.vo&&37500>c[2]&&this.yw&&0==this.On&&!this.nm&&(this.nm=z6((0,g.z)(this.sO,this),6E3));else a7(this,11)}else b!=TJa.eW.u&&a7(this,11);else if(this.Td==
a&&Y6(this),!g.pc(b)){c=this.D.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.vo=e[0];e=e[1];2==this.Ka?"c"==e[0]?(this.B=e[1],this.au=e[2],e=e[3],null!=e?this.im=e:this.im=6,this.Ka=3,this.wf&&this.wf.pC(),this.aC=S6(this,this.Yr()?this.au:null,this.qy),vIa(this)):"stop"==e[0]&&a7(this,7):3==this.Ka&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.wf&&this.wf.oC(e),this.On=0)}}};
g.k.sO=function(){null!=this.nm&&(this.nm=null,this.Td.cancel(),this.Td=null,$6(this),B6(20))};
g.k.cu=function(a){if(this.Td==a){Y6(this);this.Td=null;var b=2}else if(this.Xf==a)this.Xf=null,b=1;else return;this.Si=a.Fq;if(0!=this.Ka)if(a.ki)1==b?(b=A6,b.dispatchEvent(new lIa(b,a.bn?a.bn.length:0,g.A()-a.hp,this.bo)),X6(this),this.C.length=0):vIa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Si)){if(d=1==b)this.Xf||this.Lk||1==this.Ka||2<=this.bo?d=!1:(this.Lk=z6((0,g.z)(this.tG,this,a),wIa(this,this.bo)),this.bo++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.cK=function(a){if(!g.jb(arguments,this.Ka))throw Error("Unexpected channel state: "+this.Ka);};
g.k.nS=function(a){a?B6(2):(B6(1),xIa(this,8))};
g.k.Dx=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new N6;a.ka=!1;return a};
g.k.isActive=function(){return!!this.wf&&this.wf.isActive(this)};
g.k.Yh=function(a){var b=A6;b.dispatchEvent(new mIa(b,a))};
g.k.Yr=function(){return!(!g.ye||g.be(10))};
g.k=yIa.prototype;g.k.pC=function(){};
g.k.oC=function(){};
g.k.nC=function(){};
g.k.sx=function(){};
g.k.ZC=function(){return{}};
g.k.isActive=function(){return!0};g.k=zIa.prototype;g.k.isEmpty=function(){return g.kb(this.u)&&g.kb(this.B)};
g.k.clear=function(){this.u=[];this.B=[]};
g.k.contains=function(a){return g.jb(this.u,a)||g.jb(this.B,a)};
g.k.remove=function(a){var b=this.u;var c=(0,g.tBa)(b,a);0<=c?(g.nb(b,c),b=!0):b=!1;return b||g.ob(this.B,a)};
g.k.If=function(){for(var a=[],b=this.u.length-1;0<=b;--b)a.push(this.u[b]);var c=this.B.length;for(b=0;b<c;++b)a.push(this.B[b]);return a};g.Va(b7,g.C);g.k=b7.prototype;g.k.PQ=function(){this.zf=Math.min(3E5,2*this.zf);this.C();this.B&&this.start()};
g.k.start=function(){var a=this.zf+15E3*Math.random();this.u.Sb(a);this.B=g.A()+a};
g.k.stop=function(){this.u.stop();this.B=0};
g.k.isActive=function(){return this.u.isActive()};
g.k.reset=function(){this.u.stop();this.zf=5E3};g.Va(c7,yIa);g.k=c7.prototype;g.k.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.k.ol=function(a){return this.C.Em(a)};
g.k.V=function(a,b){return this.C.V.apply(this.C,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.fg(this.C),CIa(this),g.fg(this.B),this.B=null,this.Y=function(){return""})};
g.k.na=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.u||2!=this.u.getState()){this.P="";this.B.stop();this.F=a||null;this.D=b||0;a=this.ba+"/test";b=this.ba+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.fa),e=this.u;e&&(e.wf=null);d.wf=this;this.u=d;d7(this);if(this.u){d=g.L("ID_TOKEN");var f=this.u.Uk||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.u.Uk=f}e?(3!=e.getState()&&0==sIa(e)||e.getState(),this.u.connect(a,b,this.I,e.B,e.vo)):c?this.u.connect(a,
b,this.I,c.sessionId,c.arrayId):this.u.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Zb(c,b);this.B.isActive()||2==(this.u?this.u.getState():0)?this.K.push(c):e7(this)&&(d7(this),rIa(this.u,c))};
g.k.pC=function(){this.B.reset();this.F=null;this.D=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)rIa(this.u,a[b])}this.V("handlerOpened")};
g.k.nC=function(a){var b=2==a&&401==this.u.Si;4==a||b||this.B.start();this.V("handlerError",a)};
g.k.sx=function(a){if(!this.B.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.ZC=function(){var a={v:2};this.P&&(a.gsessionid=this.P);0!=this.D&&(a.ui=""+this.D);0!=this.R&&(a.ui=""+this.R);this.F&&g.Zb(a,this.F);return a};
g.k.oC=function(a){"S"==a[0]?this.P=a[1]:"gracefulReconnect"==a[0]?(this.B.start(),pIa(this.u)):this.V("handlerMessage",new AIa(a[0],a[1]))};
g.k.QR=function(){this.B.isActive();0==sIa(this.u)&&this.connect(this.F,this.D)};f7.prototype.D=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.F=function(a){a(Error("request timed out"))};var KIa=g.A(),i7=null,l7=Array(50),k7=-1,m7=!1;g.Va(n7,g.O);n7.prototype.tg=function(){return this.screens};
n7.prototype.contains=function(a){return!!k6(this.screens,a)};
n7.prototype.get=function(a){return a?l6(this.screens,a):null};
n7.prototype.info=function(a){j7(this.I,a)};g.u(o7,g.O);g.k=o7.prototype;g.k.start=function(){!this.u&&isNaN(this.Za)&&this.HI()};
g.k.stop=function(){this.u&&(this.u.abort(),this.u=null);isNaN(this.Za)||(g.Io(this.Za),this.Za=NaN)};
g.k.ca=function(){this.stop();g.O.prototype.ca.call(this)};
g.k.HI=function(){this.Za=NaN;this.u=g.qq(g7(this.I,"/pairing/get_screen"),{method:"POST",uc:{pairing_code:this.F},timeout:5E3,onSuccess:(0,g.z)(this.OS,this),onError:(0,g.z)(this.NS,this),Cg:(0,g.z)(this.PS,this)})};
g.k.OS=function(a,b){this.u=null;var c=b.screen||{};c.dialId=this.C;c.name=this.D;this.V("pairingComplete",new f6(c))};
g.k.NS=function(a){this.u=null;a.status&&404==a.status?this.B>=VJa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=VJa[this.B],this.Za=g.Go((0,g.z)(this.HI,this),a),this.B++):this.V("pairingFailed",Error("Server error "+a.status))};
g.k.PS=function(){this.u=null;this.V("pairingFailed",Error("Server not responding"))};
var VJa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Va(q7,n7);g.k=q7.prototype;g.k.start=function(){p7(this)&&this.V("screenChange");!g.lu("yt-remote-lounge-token-expiration")&&OIa(this);g.Io(this.u);this.u=g.Go((0,g.z)(this.start,this),1E4)};
g.k.add=function(a,b){p7(this);LIa(this,a);r7(this,!1);this.V("screenChange");b(a);a.token||OIa(this)};
g.k.remove=function(a,b){var c=p7(this);NIa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.k.ww=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.k.ca=function(){g.Io(this.u);q7.Kd.ca.call(this)};
g.k.LK=function(a){p7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.I,"Missed "+b+" lounge tokens.")};
g.k.KK=function(a){j7(this.I,"Requesting lounge tokens failed: "+a)};g.u(t7,g.O);g.k=t7.prototype;g.k.start=function(){var a=parseInt(g.lu("yt-remote-fast-check-period")||"0",10);(this.D=g.A()-144E5<a?0:a)?v7(this):(this.D=g.A()+3E5,g.ku("yt-remote-fast-check-period",this.D),this.hA())};
g.k.isEmpty=function(){return g.Sb(this.u)};
g.k.update=function(){s7("Updating availability on schedule.");var a=this.I(),b=g.Fb(this.u,function(c,d){return c&&!!l6(a,d)},this);
u7(this,b)};
g.k.ca=function(){g.Io(this.C);this.C=NaN;this.B&&(this.B.abort(),this.B=null);g.O.prototype.ca.call(this)};
g.k.hA=function(){g.Io(this.C);this.C=NaN;this.B&&this.B.abort();var a=RIa(this);if(b6(a)){var b=g7(this.F,"/pairing/get_screen_availability");this.B=h7(this.F,b,{lounge_token:g.Mb(a).join(",")},(0,g.z)(this.xQ,this,a),(0,g.z)(this.wQ,this))}else u7(this,{}),v7(this)};
g.k.xQ=function(a,b){this.B=null;var c=g.Mb(RIa(this));if(g.Ab(c,g.Mb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.Dd("Changing Screen set during request."),this.hA()};
g.k.wQ=function(a){this.Dd("Screen availability failed: "+a);this.B=null;v7(this)};
g.k.Dd=function(a){j7("OnlineScreenService",a)};g.Va(w7,n7);g.k=w7.prototype;g.k.start=function(){this.B.start();this.u.start();this.screens.length&&(this.V("screenChange"),this.u.isEmpty()||this.V("onlineScreenChange"))};
g.k.add=function(a,b,c){this.B.add(a,b,c)};
g.k.remove=function(a,b,c){this.B.remove(a,b,c);this.u.update()};
g.k.ww=function(a,b,c,d){this.B.contains(a)?this.B.ww(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.I,a),d(Error(a)))};
g.k.tg=function(a){return a?this.screens:g.qb(this.screens,g.Ke(this.C,function(b){return!this.contains(b)},this))};
g.k.II=function(){return g.Ke(this.tg(!0),function(a){return!!this.u.u[a.id]},this)};
g.k.JI=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(h){g.fg(f);d(x7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.fg(f);e(h)});
f.start();return(0,g.z)(f.stop,f)};
g.k.QS=function(a,b,c,d){g.qq(g7(this.F,"/pairing/get_screen"),{method:"POST",uc:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var h=new f6(f.screen||{});if(!h.name||VIa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);VIa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(x7(this,h))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
Cg:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.k.ca=function(){g.fg(this.B);g.fg(this.u);w7.Kd.ca.call(this)};
g.k.RK=function(){WIa(this);this.V("screenChange");this.u.update()};
w7.prototype.dispose=w7.prototype.dispose;g.Va(z7,g.O);g.k=z7.prototype;g.k.getScreen=function(){return this.K};
g.k.Bv=function(a){this.K=a;this.V("sessionScreen",this.K)};
g.k.Ag=function(a){this.na()||(a&&A7(this,""+a),this.K=null,this.V("sessionScreen",null))};
g.k.info=function(a){j7(this.ba,a)};
g.k.LI=function(){return null};
g.k.tA=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.ca=function(){this.tA("");z7.Kd.ca.call(this)};g.u(B7,z7);g.k=B7.prototype;g.k.sA=function(a){if(this.B){if(this.B==a)return;A7(this,"Overriding cast sesison with new session object");this.B.removeUpdateListener(this.F);this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.B=a;this.B.addUpdateListener(this.F);this.B.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);YIa(this)};
g.k.wo=function(a){this.info("launchWithParams no-op for Cast: "+g.Kj(a))};
g.k.stop=function(){this.B?this.B.stop((0,g.z)(function(){this.Ag()},this),(0,g.z)(function(){this.Ag(Error("Failed to stop receiver app."))},this)):this.Ag(Error("Stopping cast device witout session."))};
g.k.tA=function(){};
g.k.ca=function(){this.info("disposeInternal");g.Io(this.C);this.C=0;this.B&&(this.B.removeUpdateListener(this.F),this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.B=null;z7.prototype.ca.call(this)};
g.k.mR=function(a,b){if(!this.na())if(b){var c=x6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kj(c));switch(d){case "mdxSessionStatus":XIa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.k.pD=function(a,b,c,d){UIa(this.R,this.u.label,a,this.u.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Go((0,g.z)(this.pD,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.LI=function(){return this.B};
g.k.RS=function(a){this.na()||a||(A7(this,"Cast session died."),this.Ag())};g.u(C7,z7);g.k=C7.prototype;g.k.sA=function(a){this.C=a;this.C.addUpdateListener(this.Y)};
g.k.wo=function(a){this.X=a;this.F()};
g.k.stop=function(){this.B();this.B=g.Ka;g.Io(this.D);this.C?this.C.stop((0,g.z)(this.Ag,this,null),(0,g.z)(this.Ag,this,"Failed to stop DIAL device.")):this.Ag()};
g.k.ca=function(){this.B();this.B=g.Ka;g.Io(this.D);this.C&&this.C.removeUpdateListener(this.Y);this.C=null;z7.prototype.ca.call(this)};
g.k.VS=function(a){this.na()||a||(A7(this,"DIAL session died."),this.B(),this.B=g.Ka,this.Ag())};
g.k.Ey=function(a){this.P=j6();if(this.X){var b=new chrome.cast.DialLaunchResponse(!0,$Ia(this));a(b);ZIa(this)}else this.F=(0,g.z)(function(){g.Io(this.D);this.F=g.Ka;this.D=NaN;var c=new chrome.cast.DialLaunchResponse(!0,$Ia(this));a(c);ZIa(this)},this),this.D=g.Go((0,g.z)(function(){this.F()},this),100)};
g.k.iL=function(a,b,c){UIa(this.R,this.I.receiver.label,a,this.u.friendlyName,(0,g.z)(function(d){d&&d.token?(this.Bv(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Ey(b,c)},this),(0,g.z)(function(d){A7(this,"Failed to get DIAL screen: "+d);
this.Ey(b,c)},this))};g.u(D7,z7);D7.prototype.stop=function(){this.Ag()};
D7.prototype.sA=function(){};
D7.prototype.wo=function(){g.Io(this.B);this.B=NaN;var a=l6(this.R.tg(),this.u.label);a?this.Bv(a):this.Ag(Error("No such screen"))};
D7.prototype.ca=function(){g.Io(this.B);this.B=NaN;z7.prototype.ca.call(this)};g.u(E7,g.O);g.k=E7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.K);this.R||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.z)(this.hQ,this);c=new chrome.cast.ApiConfig(c,(0,g.z)(this.oG,this),f,d,e);c.customDialLaunchCallback=(0,g.z)(this.OO,this);chrome.cast.initialize(c,(0,g.z)(function(){this.na()||
(chrome.cast.addReceiverActionListener(this.D),HIa(),this.B.subscribe("onlineScreenChange",(0,g.z)(this.KI,this)),this.C=bJa(this),chrome.cast.setCustomReceivers(this.C,g.Ka,(0,g.z)(function(h){this.Dd("Failed to set initial custom receivers: "+g.Kj(h))},this)),this.V("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.z)(function(h){this.Dd("Failed to initialize API: "+g.Kj(h));
b(!1)},this))};
g.k.VR=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.u){var c=this.u.getScreen();if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.u.u.friendlyName),H7(this,null)}if(a&&b){if(!this.u){c=l6(this.B.tg(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=aJa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,
g.Ka,(0,g.z)(function(e){this.Dd("Failed to set initial custom receivers: "+g.Kj(e))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.B,d),!0)}this.u.tA(b)}else F7("setConnectedScreenStatus: no screen.")};
g.k.WR=function(a){this.na()?this.Dd("Setting connection data on disposed cast v2"):this.u?this.u.wo(a):this.Dd("Setting connection data without a session")};
g.k.US=function(){this.na()?this.Dd("Stopping session on disposed cast v2"):this.u?(this.u.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.oG,this),(0,g.z)(this.zQ,this))};
g.k.ca=function(){this.B.unsubscribe("onlineScreenChange",(0,g.z)(this.KI,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=EIa,b=g.Ja("yt.mdx.remote.debug.handlers_");g.ob(b||[],a);g.fg(this.u);g.O.prototype.ca.call(this)};
g.k.Dd=function(a){j7("Controller",a)};
g.k.qG=function(a,b){this.u==a&&(b||H7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.k.eQ=function(a,b){if(!this.na())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.u)if(this.u.u.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.u.u.friendlyName),this.u.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.u.getScreen()&&this.V("yt-remote-cast2-session-change",this.u.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.B,a));break;case chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.B,a,this.I));break;case chrome.cast.ReceiverType.CAST:H7(this,new B7(this.B,a));break;default:this.Dd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.u&&this.u.u.label==a.label?this.u.stop():this.Dd("Stopping receiver w/o session: "+a.friendlyName)}else this.Dd("onReceiverAction_ called without receiver.")};
g.k.OO=function(a){if(this.na())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Dd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.u?this.u.u:null;if(!c||c.label!=b.label)return this.Dd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.u.getScreen())return F7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.u.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Dd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.B,b,this.I))}b=this.u;b.I=a;return b.I.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.iL,b,(b.I.extraData||{}).screenId||null)):new Promise((0,g.z)(b.Ey,b))};
g.k.oG=function(a){if(!this.na()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.u)if(b.receiverType==chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.B,b),!0);else{this.Dd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.u.u,d=l6(this.B.tg(),c.label);d&&g6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.fg(this.u),this.u=new B7(this.B,b),this.u.subscribe("sessionScreen",(0,g.z)(this.qG,this,this.u)),this.u.wo(null));this.u.sA(a)}}};
g.k.SS=function(){return this.u?this.u.LI():null};
g.k.zQ=function(a){this.na()||(this.Dd("Failed to estabilish a session: "+g.Kj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.k.hQ=function(a){F7("Receiver availability updated: "+a);if(!this.na()){var b=G7(this);this.F=a==chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.V("yt-remote-cast2-availability-change",G7(this))}};
g.k.KI=function(){this.na()||(this.C=bJa(this),F7("Updating custom receivers: "+g.Kj(this.C)),chrome.cast.setCustomReceivers(this.C,g.Ka,(0,g.z)(function(){this.Dd("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.WR;E7.prototype.setConnectedScreenStatus=E7.prototype.VR;E7.prototype.stopSession=E7.prototype.US;E7.prototype.getCastSession=E7.prototype.SS;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.k=S7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.u=a.trackData,this.Ui=a.hasPrevious,this.hasNext=a.hasNext,this.R=a.playerTime,this.K=a.playerTimeAt,this.F=a.seekableStart,this.B=a.seekableEnd,this.I=a.duration,this.P=a.loadedTime,this.D=a.liveIngestionTime,this.C=!isNaN(this.D))};
g.k.Hb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.hi=function(a){this.I=isNaN(a)?0:a};
g.k.getDuration=function(){return this.C?this.I+U7(this):this.I};
g.k.clone=function(){return new S7(Y7(this))};g.u($7,g.O);g.k=$7.prototype;g.k.getState=function(){return this.Ka};
g.k.play=function(){b8(this)?(this.u?this.u.play(null,g.Ka,g8(this,"play")):f8(this,"play"),e8(this,1,W7(a8(this))),this.V("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){b8(this)?(this.u?this.u.pause(null,g.Ka,g8(this,"pause")):f8(this,"pause"),e8(this,2,W7(a8(this))),this.V("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(b8(this)){if(this.u){var b=a8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Hb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ka,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.V("remotePlayerChange")}else c8(this,g.Ta(this.seekTo,a))};
g.k.stop=function(){if(b8(this)){this.u?this.u.stop(null,g.Ka,g8(this,"stopVideo")):f8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);d8(this,a);this.V("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(b8(this)){var c=a8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.z)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Dd("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.z)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Dd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Ta(this.setVolume,a,b))};
g.k.GI=function(a,b){if(b8(this)){var c=a8(this),d={videoId:a};b&&(c.u={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kj(b.style),g.Zb(d,c.u));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Ta(this.GI,a,b))};
g.k.setAudioTrack=function(a,b){if(b8(this)){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=a8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Ta(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=a8(this);c=c||0;var m={videoId:a,currentIndex:c};X7(l,a,c);void 0!==b&&(V7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Kj(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.Kv=function(a,b){if(b8(this)){if(a&&b){var c=a8(this);X7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Ta(this.Kv,a,b))};
g.k.nextVideo=function(a,b){if(b8(this)){if(a&&b){var c=a8(this);X7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Ta(this.nextVideo,a,b))};
g.k.KC=function(){b8(this)?f8(this,"dismissAutoplay"):c8(this,this.KC)};
g.k.dispose=function(){if(3!=this.Ka){var a=this.Ka;this.Ka=3;this.V("proxyStateChange",a,this.Ka)}g.O.prototype.dispose.call(this)};
g.k.ca=function(){oJa(this);this.C=null;this.D.clear();Z7(this,null);g.O.prototype.ca.call(this)};
g.k.wA=function(a){if((a!=this.Ka||2==a)&&3!=this.Ka&&0!=a){var b=this.Ka;this.Ka=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,g.kb(b.u)&&(b.u=b.B,b.u.reverse(),b.B=[]),a.u.pop().apply(this);else 3==a&&this.dispose()}};
g.k.aQ=function(a,b){this.V(a,b)};
g.k.zO=function(a){if(!a)this.tr(null),Z7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.tr=function(a){j7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.K);if(this.u=a)this.u.addUpdateListener(this.K),pJa(this),this.V("remotePlayerChange")};
g.k.yO=function(a){a?(pJa(this),this.V("remotePlayerChange")):this.tr(null)};
g.k.NA=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.GO=function(){var a=lJa();a&&Z7(this,a)};
g.k.Dd=function(a){j7("CP",a)};g.u(h8,g.O);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Lb.listId=c);this.Lb.videoId=d;this.Lb.index=h||0;this.Lb.state=3;V7(this.Lb,m);this.D="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.Kj(l));this.u.connect({method:"setPlaylist",
params:g.Kj(l)},a,yHa())}else i8("Connecting without params"),this.u.connect({},a,yHa());rJa(this)};
g.k.dispose=function(){this.na()||(this.V("beforeDispose"),j8(this,3));g.O.prototype.dispose.call(this)};
g.k.ca=function(){k8(this);m8(this);l8(this);g.Io(this.K);this.K=NaN;g.Io(this.R);this.R=NaN;this.C=null;g.dp(this.ba);this.ba.length=0;this.u.dispose();g.O.prototype.ca.call(this);this.D=this.I=this.B=this.Lb=this.u=null};
g.k.FK=function(){this.Wn(2)};
g.k.DO=function(){i8("Channel opened");this.Y&&(this.Y=!1,l8(this),this.X=g.Go((0,g.z)(function(){i8("Timing out waiting for a screen.");this.Wn(1)},this),15E3));
CHa(BIa(this.u),this.fa)};
g.k.AO=function(){i8("Channel closed");isNaN(this.F)?q6(!0):q6();this.dispose()};
g.k.BO=function(a){q6();isNaN(this.zq())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.Y=!0,i8("Channel error: "+a+" with reconnection in "+this.zq()+" ms"),j8(this,2))};
g.k.CO=function(a){a.params?i8("Received: action="+a.action+", params="+g.Kj(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.B=g.Oc(a,function(c){return new e6(c)});
a=!!g.fb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
uJa(this,a);break;case "loungeScreenDisconnected":g.pb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
uJa(this,!1);break;case "remoteConnected":var b=new e6(x6(a.params.device));g.fb(this.B,function(c){return b?c.id==b.id:!1})||iHa(this.B,b);
break;case "remoteDisconnected":b=new e6(x6(a.params.device));g.pb(this.B,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":wJa(this,a);break;case "nowPlaying":yJa(this,a);break;case "onStateChange":xJa(this,a);break;case "onAdStateChange":zJa(this,a);break;case "onVolumeChanged":AJa(this,a);break;case "onSubtitlesTrackChanged":vJa(this,a);break;case "nowAutoplaying":BJa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.V("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.D=
a.params.autoplayMode;this.V("autoplayModeChange",this.D);"DISABLED"==this.D&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":CJa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.MR=function(){if(this.C){var a=this.C;this.C=null;this.Lb.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.xK=function(){var a=3;this.na()||(a=0,isNaN(this.zq())?e7(this.u)&&isNaN(this.F)&&(a=1):a=2);return a};
g.k.Wn=function(a){i8("Disconnecting with "+a);k8(this);this.V("beforeDisconnect",a);1==a&&q6();CIa(this.u,a);this.dispose()};
g.k.vK=function(){var a=this.Lb;this.C&&(a=this.Lb.clone(),X7(a,this.C,a.index));return Y7(a)};
g.k.XR=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.Lb.videoId&&(this.C=b.videoId,g.Io(this.K),this.K=g.Go((0,g.z)(this.MR,this),5E3));var c=[];this.Lb.listId==b.listId&&this.Lb.videoId==b.videoId&&this.Lb.index==b.index||c.push("remoteQueueChange");this.Lb.playerState==b.playerState&&this.Lb.volume==b.volume&&this.Lb.muted==b.muted&&W7(this.Lb)==W7(b)&&g.Kj(this.Lb.u)==g.Kj(b.u)||c.push("remotePlayerChange");this.Lb.reset(a);g.Cb(c,function(d){this.V(d)},this)};
g.k.oD=function(){var a=this.u.I.id,b=g.fb(this.B,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.zq=function(){var a=this.u;return a.B.isActive()?a.B.B-g.A():NaN};
g.k.mK=function(){return this.D||"UNSUPPORTED"};
g.k.nK=function(){return this.I||""};
g.k.MS=function(){if(!isNaN(this.zq())){var a=this.u.B;g.kn(a.u);a.start()}};
g.k.TR=function(a,b){n8(this,a,b);tJa(this)};
g.k.FI=function(){var a=g.xq("SID","")||"",b=g.xq("SAPISID","")||"",c=g.xq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.sf(g.Xe(a),2);b=g.sf(g.Xe(b),2);c=g.sf(g.Xe(c),2);return g.sf(g.Xe(a+","+b+","+c),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.ol;h8.prototype.getProxyState=h8.prototype.xK;h8.prototype.disconnect=h8.prototype.Wn;h8.prototype.getPlayerContextData=h8.prototype.vK;h8.prototype.setPlayerContextData=h8.prototype.XR;h8.prototype.getOtherConnectedRemoteId=h8.prototype.oD;h8.prototype.getReconnectTimeout=h8.prototype.zq;h8.prototype.getAutoplayMode=h8.prototype.mK;h8.prototype.getAutoplayVideoId=h8.prototype.nK;h8.prototype.reconnect=h8.prototype.MS;
h8.prototype.sendMessage=h8.prototype.TR;h8.prototype.getXsrfToken=h8.prototype.FI;g.u(o8,n7);g.k=o8.prototype;g.k.tg=function(a){return this.yf.$_gs(a)};
g.k.contains=function(a){return!!this.yf.$_c(a)};
g.k.get=function(a){return this.yf.$_g(a)};
g.k.start=function(){this.yf.$_st()};
g.k.add=function(a,b,c){this.yf.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.yf.$_r(a,b,c)};
g.k.ww=function(a,b,c,d){this.yf.$_un(a,b,c,d)};
g.k.ca=function(){for(var a=0,b=this.u.length;a<b;++a)this.yf.$_ubk(this.u[a]);this.u.length=0;this.yf=null;n7.prototype.ca.call(this)};
g.k.EL=function(){this.V("screenChange")};
g.k.HP=function(){this.V("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.QS;w7.prototype.$_gsppc=w7.prototype.JI;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.ww;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.tg;w7.prototype.$_gos=w7.prototype.II;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.ol;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.u(I8,g.C);g.k=I8.prototype;g.k.ca=function(){g.C.prototype.ca.call(this);this.u.stop();this.C.stop();this.R.stop();this.Y();var a=this.yb;a.unsubscribe("proxyStateChange",this.lG,this);a.unsubscribe("remotePlayerChange",this.yr,this);a.unsubscribe("remoteQueueChange",this.Cv,this);a.unsubscribe("previousNextChange",this.iG,this);a.unsubscribe("nowAutoplaying",this.dG,this);a.unsubscribe("autoplayDismissed",this.EF,this);this.yb=this.B=null};
g.k.SE=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.yb.Ka)if(J8(this)){if(!a8(this.yb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":a8(this.yb).Hb()?this.yb.pause():this.yb.play();break;case "control_play":this.yb.play();break;case "control_pause":this.yb.pause();break;case "control_seek":this.K.BE(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.wO=function(a){this.R.CK(a)};
g.k.BS=function(a){this.SE("control_subtitles_set_track",g.Sb(a)?null:a)};
g.k.OH=function(){var a=this.J.getOption("captions","track");g.Sb(a)||K8(this,a)};
g.k.tc=function(a){this.B.tc(a,this.J.getVideoData().lengthSeconds)};
g.k.lP=function(){g.Sb(this.D)||NJa(this,this.D);this.F=!1};
g.k.lG=function(a,b){this.C.stop();2===b&&this.JH()};
g.k.yr=function(){if(J8(this)){this.u.stop();var a=a8(this.yb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.Ke=1;break;case 1082:case 1083:this.B.Ke=0;break;default:this.B.Ke=-1}switch(a.playerState){case 1081:case 1:this.vb(new g.AM(8));this.IH();break;case 1085:case 3:this.vb(new g.AM(9));break;case 1083:case 0:this.vb(new g.AM(2));this.K.stop();this.tc(this.J.getVideoData().lengthSeconds);break;case 1084:this.vb(new g.AM(4));break;case 2:this.vb(new g.AM(4));this.tc(W7(a));
break;case -1:this.vb(new g.AM(64));break;case -1E3:this.vb(new g.AM(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=a8(this.yb).u;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,NJa(this,a));a=a8(this.yb);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.P.isActive()||this.pI()}else MJa(this)};
g.k.iG=function(){this.J.V("mdxpreviousnextchange")};
g.k.Cv=function(){J8(this)||MJa(this)};
g.k.dG=function(a){isNaN(a)||this.J.V("mdxnowautoplaying",a)};
g.k.EF=function(){this.J.V("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.yb.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a8(this.yb).playerState?L8(this,a):b&&this.yb.seekTo(a)};
g.k.pI=function(){var a=this;if(J8(this)){var b=a8(this.yb);this.events.Mb(this.X);b.muted?this.J.mute():this.J.unMute();this.J.setVolume(b.volume);this.X=this.events.N(this.J,"onVolumeChange",function(c){LJa(a,c)})}};
g.k.IH=function(){this.u.stop();if(!this.yb.na()){var a=a8(this.yb);a.Hb()&&this.vb(new g.AM(8));this.tc(W7(a));this.u.start()}};
g.k.JH=function(){this.C.stop();this.u.stop();var a=this.yb.C.getReconnectTimeout();2==this.yb.Ka&&!isNaN(a)&&this.C.start()};
g.k.vb=function(a){this.C.stop();var b=this.I;if(!g.FM(b,a)){var c=g.U(a,2);c!==g.U(this.I,2)&&g.F0(this.J.app,c);this.I=a;PJa(this.B,b,a)}};g.u(M8,g.V);M8.prototype.Cc=function(){this.u.show()};
M8.prototype.nb=function(){this.u.hide()};
M8.prototype.B=function(){g.RL("https://support.google.com/youtube/answer/7640706")};
M8.prototype.C=function(){d6("mdx-manual-pairing-popup-ok");this.nb()};g.u(N8,g.V);N8.prototype.Cc=function(){this.u.show()};
N8.prototype.nb=function(){this.u.hide()};
N8.prototype.B=function(){d6("mdx-privacy-popup-cancel");this.nb()};
N8.prototype.C=function(){d6("mdx-privacy-popup-confirm");this.nb()};g.u(O8,g.V);O8.prototype.B=function(a){OJa(this,a.state)};g.u(P8,g.vX);P8.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.Fl=g.Db(a,this.u,this),g.wX(this,g.Oc(a,this.u)),a=this.J.getOption("remote","currentReceiver"),this.Nc(this.u(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.u=function(a){return a.key};
P8.prototype.Uh=function(a){return"cast-selector-receiver"===a?"Cast...":this.Fl[a].name};
P8.prototype.bf=function(a){g.vX.prototype.bf.call(this,a);this.J.setOption("remote","currentReceiver",this.Fl[a]);this.Xa.nb()};g.u(Q8,g.IS);g.k=Q8.prototype;
g.k.create=function(){var a=this.player.T(),b=g.nD(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.Q(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.Q(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.Q(a.experiments,"enable_cast_short_lived_lounge_token")};GJa(b,a);this.subscriptions.push(g.No("yt-remote-before-disconnect",this.uO,this));this.subscriptions.push(g.No("yt-remote-connection-change",this.iQ,this));this.subscriptions.push(g.No("yt-remote-receiver-availability-change",
this.kG,this));this.subscriptions.push(g.No("yt-remote-auto-connect",this.gQ,this));this.subscriptions.push(g.No("yt-remote-receiver-resumed",this.fQ,this));this.subscriptions.push(g.No("mdx-privacy-popup-confirm",this.CR,this));this.subscriptions.push(g.No("mdx-privacy-popup-cancel",this.BR,this));this.subscriptions.push(g.No("mdx-manual-pairing-popup-ok",this.yL,this));this.kG()};
g.k.load=function(){this.player.cancelPlayback();g.IS.prototype.load.call(this);this.Ai=new I8(this,this.player,this.yb);var a=(a=KJa())?a.currentTime:0;var b=E8()?new $7(z8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!==a&&this.tc(a);PJa(this,this.Qc,this.Qc);g.N0(this.player.app,6)};
g.k.unload=function(){this.player.V("mdxautoplaycanceled");this.Ik=this.Rh;g.gg(this.Ai,this.yb);this.yb=this.Ai=null;g.IS.prototype.unload.call(this);g.N0(this.player.app,5);R8(this)};
g.k.ca=function(){g.Oo(this.subscriptions);g.IS.prototype.ca.call(this)};
g.k.jj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Ai.SE.apply(this.Ai,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.Ke};
g.k.yK=function(){return this.loaded?this.Ai.suggestion:null};
g.k.Ui=function(){return this.yb?a8(this.yb).Ui:!1};
g.k.hasNext=function(){return this.yb?a8(this.yb).hasNext:!1};
g.k.tc=function(a,b){this.nE=a||0;this.player.V("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.nE};
g.k.getProgressState=function(){var a=a8(this.yb),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Ie():!a.isAdPlaying()&&this.player.Ie(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.D+U7(a):a.D,isAtLiveHead:1>=(a.C?a.B+U7(a):a.B)-this.getCurrentTime(),loaded:a.P,seekableEnd:a.C?a.B+U7(a):a.B,seekableStart:0<a.F?a.F+
U7(a):a.F}};
g.k.nextVideo=function(){this.yb&&this.yb.nextVideo()};
g.k.Kv=function(){this.yb&&this.yb.Kv()};
g.k.uO=function(a){1===a&&(this.Sz=this.yb?a8(this.yb):null)};
g.k.iQ=function(){var a=E8()?new $7(z8(),void 0):null;if(a){var b=this.Ik;this.loaded&&this.unload();this.yb=a;this.Sz=null;b.key!==this.Rh.key&&(this.Ik=b,this.load())}else g.fg(this.yb),this.yb=null,this.loaded&&(this.unload(),(a=this.Sz)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.kG=function(){var a=[this.Rh],b=a.concat,c=HJa();O7()&&g.lu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Fl=b.call(a,c);a=A8()||this.Rh;S8(this,a);this.player.xa("onMdxReceiversChange")};
g.k.gQ=function(){var a=A8();S8(this,a)};
g.k.fQ=function(){this.Ik=A8()};
g.k.CR=function(){this.Br=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.BR=function(){this.Br=!1;R8(this);S8(this,this.Rh);this.Ik=this.Rh;G8=!1;H8=null;this.player.playVideo()};
g.k.yL=function(){this.Ku=!0;R8(this);g.ku("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.Be=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Fl;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q7():S8(this,b)),this.loaded?this.Ik:this.Rh;case "quickCast":return 2===this.Fl.length&&"cast-selector-receiver"===this.Fl[1].key?(b&&Q7(),!0):!1}};
g.k.NA=function(){this.yb.NA()};
g.k.ji=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.pU.remote=Q8;})(_yt_player);
